package cvmatch

// Code generated by `make regolden REASON="..."`. DO NOT EDIT BY HAND.
//
// Recorded: 2026-07-26 — Reason: 7.2a: column FFTs switch to the no-FMA radix-4 engine (bottom head stage; rows stay radix-2)
//
// One constant per goldenCases entry, in order. These pin the
// implementation's own deterministic output (self-identity across
// architectures, build modes and thread counts); validity vs OpenCV is
// established by the bench tolerance parity gates at record time.
var goldenHashes = [...]uint64{
	0x84a9a15ff5156bde, // 101 grayscale
	0x7f737028598d137b, // 102 full RGBA
	0xe483762419f9b1e6, // 103 RGBA with alpha skipped (cn=3, step=4)
	0x3ebb09558058c6bc, // 104 strided rows (sub-image)
	0x5dad9be90c411aaf, // 105 template == image (1x1 result)
	0x7711e78701385195, // 106 1x1 template
	0x5b3479d8c3f8e83b, // 107 multi-block FFT tiling
	0x99faba63e357f5d0, // 108 packed RGB (step==cn=3, scalar pack fallback)
	0xccad1a118899c04f, // 109 tall template, tiny result width
	0x99534488138e0635, // 110 flat-window guard canary
}
