package cvmatch

// Code generated by `make regolden REASON="..."`. DO NOT EDIT BY HAND.
//
// Recorded: 2026-07-17 — Reason: normalize-f32 v2: cn=1 spills the raw window sum with the template mean folded into the tail's num scale (Phase 7.3)
//
// One constant per goldenCases entry, in order. These pin the
// implementation's own deterministic output (self-identity across
// architectures, build modes and thread counts); validity vs OpenCV is
// established by the bench tolerance parity gates at record time.
var goldenHashes = [...]uint64{
	0x11f97b0dd375afcb, // 101 grayscale
	0xc137cebd99bb61c3, // 102 full RGBA
	0x0f97f98d25e3100a, // 103 RGBA with alpha skipped (cn=3, step=4)
	0x38ca62586c46f22b, // 104 strided rows (sub-image)
	0x5dad9be90c411aaf, // 105 template == image (1x1 result)
	0x7711e78701385195, // 106 1x1 template
	0x7fc036f81ad4d0e1, // 107 multi-block FFT tiling
	0x981b720d6fb8db83, // 108 packed RGB (step==cn=3, scalar pack fallback)
	0xa7037a5c127ea19d, // 109 tall template, tiny result width
	0x99534488138e0635, // 110 flat-window guard canary
}
