// Code generated by internal/simd/_gen/gen.py from the kernels_*.S sources. DO NOT EDIT.
// Regenerate with: go generate ./internal/simd

//go:build gc && cvmatch_asm

#include "textflag.h"

// NEON kernels for arm64 — the twins of the AVX2
// kernels in simd_amd64.s, bit-identical to the generic Go loops (see
// kernels.S in this directory for the annotated source). Go's assembler
// has no un-fused vector FP arithmetic, so each body below is a generated
// WORD stream; this template owns the TEXT frames and every argument
// load/store so `go vet` still checks frame offsets. The bodies use only
// x0-x15 and v0-v31, never the stack, and never fmla/fmls — every float
// op is a distinct IEEE single-rounded instruction.

// func FFTStages(a []complex64, tw []complex64, inverse bool)
TEXT ·FFTStages(SB), NOSPLIT, $0-49
	MOVD  a_base+0(FP), R0
	MOVD  a_len+8(FP), R1
	MOVD  tw_base+24(FP), R2
	MOVBU inverse+48(FP), R3
	WORD $0x53010069 // lsl w9, w3, #31
	WORD $0x4e040d3d // dup v29.4s, w9
	WORD $0x52b00009 // mov w9, #-0x80000000
	WORD $0x4e080d3a // dup v26.2d, x9
	WORD $0xd2f00009 // mov x9, #-0x8000000000000000
	WORD $0xf2b00009 // movk x9, #0x8000, lsl #16
	WORD $0x6f00e419 // movi v25.2d, #0000000000000000
	WORD $0x4e181d39 // mov v25.d[1], x9
	WORD $0xfd40045e // ldr d30, [x2, #0x8]
	WORD $0x4e0407db // dup v27.4s, v30.s[0]
	WORD $0x4e0c07dc // dup v28.4s, v30.s[1]
	WORD $0x6e3d1f9c // eor v28.16b, v28.16b, v29.16b
	WORD $0x3dc0045e // ldr q30, [x2, #0x10]
	WORD $0x4e9e2bd7 // trn1 v23.4s, v30.4s, v30.4s
	WORD $0x4e9e6bd8 // trn2 v24.4s, v30.4s, v30.4s
	WORD $0x6e3d1f18 // eor v24.16b, v24.16b, v29.16b
	WORD $0xaa0003e9 // mov x9, x0
	WORD $0xaa0103ea // mov x10, x1
	WORD $0xad401123 // ldp q3, q4, [x9]
	WORD $0x4ea00865 // rev64 v5.4s, v3.4s
	WORD $0x6e3bdc66 // fmul v6.4s, v3.4s, v27.4s
	WORD $0x6e3cdca7 // fmul v7.4s, v5.4s, v28.4s
	WORD $0x6e3a1ce7 // eor v7.16b, v7.16b, v26.16b
	WORD $0x4e27d4c6 // fadd v6.4s, v6.4s, v7.4s
	WORD $0x4e1804c8 // dup v8.2d, v6.d[1]
	WORD $0x6e391d08 // eor v8.16b, v8.16b, v25.16b
	WORD $0x4e080469 // dup v9.2d, v3.d[0]
	WORD $0x4e28d523 // fadd v3.4s, v9.4s, v8.4s
	WORD $0x4ea00885 // rev64 v5.4s, v4.4s
	WORD $0x6e3bdc86 // fmul v6.4s, v4.4s, v27.4s
	WORD $0x6e3cdca7 // fmul v7.4s, v5.4s, v28.4s
	WORD $0x6e3a1ce7 // eor v7.16b, v7.16b, v26.16b
	WORD $0x4e27d4c6 // fadd v6.4s, v6.4s, v7.4s
	WORD $0x4e1804c8 // dup v8.2d, v6.d[1]
	WORD $0x6e391d08 // eor v8.16b, v8.16b, v25.16b
	WORD $0x4e080489 // dup v9.2d, v4.d[0]
	WORD $0x4e28d524 // fadd v4.4s, v9.4s, v8.4s
	WORD $0x4ea00885 // rev64 v5.4s, v4.4s
	WORD $0x6e37dc86 // fmul v6.4s, v4.4s, v23.4s
	WORD $0x6e38dca7 // fmul v7.4s, v5.4s, v24.4s
	WORD $0x6e3a1ce7 // eor v7.16b, v7.16b, v26.16b
	WORD $0x4e27d4c6 // fadd v6.4s, v6.4s, v7.4s
	WORD $0x4e26d46a // fadd v10.4s, v3.4s, v6.4s
	WORD $0x4ea6d46b // fsub v11.4s, v3.4s, v6.4s
	WORD $0xac812d2a // stp q10, q11, [x9], #0x20
	WORD $0xf100114a // subs x10, x10, #0x4
	WORD $0x54fffc81 // b.ne <FFTStages+0x48>
	WORD $0xd2800084 // mov x4, #0x4
	WORD $0xeb01009f // cmp x4, x1
	WORD $0x540004ea // b.ge <FFTStages+0x160>
	WORD $0x8b040c45 // add x5, x2, x4, lsl #3
	WORD $0xd2800006 // mov x6, #0x0
	WORD $0x8b060c07 // add x7, x0, x6, lsl #3
	WORD $0x8b040ce8 // add x8, x7, x4, lsl #3
	WORD $0xaa0503e9 // mov x9, x5
	WORD $0xaa0403ea // mov x10, x4
	WORD $0xad402901 // ldp q1, q10, [x8]
	WORD $0xacc13122 // ldp q2, q12, [x9], #0x20
	WORD $0x4e822843 // trn1 v3.4s, v2.4s, v2.4s
	WORD $0x4e826844 // trn2 v4.4s, v2.4s, v2.4s
	WORD $0x6e3d1c84 // eor v4.16b, v4.16b, v29.16b
	WORD $0x4ea00825 // rev64 v5.4s, v1.4s
	WORD $0x6e23dc26 // fmul v6.4s, v1.4s, v3.4s
	WORD $0x6e24dca7 // fmul v7.4s, v5.4s, v4.4s
	WORD $0x6e3a1ce7 // eor v7.16b, v7.16b, v26.16b
	WORD $0x4e27d4c6 // fadd v6.4s, v6.4s, v7.4s
	WORD $0x4e8c298d // trn1 v13.4s, v12.4s, v12.4s
	WORD $0x4e8c698e // trn2 v14.4s, v12.4s, v12.4s
	WORD $0x6e3d1dce // eor v14.16b, v14.16b, v29.16b
	WORD $0x4ea0094f // rev64 v15.4s, v10.4s
	WORD $0x6e2ddd50 // fmul v16.4s, v10.4s, v13.4s
	WORD $0x6e2eddf1 // fmul v17.4s, v15.4s, v14.4s
	WORD $0x6e3a1e31 // eor v17.16b, v17.16b, v26.16b
	WORD $0x4e31d610 // fadd v16.4s, v16.4s, v17.4s
	WORD $0xad402ce0 // ldp q0, q11, [x7]
	WORD $0x4e26d408 // fadd v8.4s, v0.4s, v6.4s
	WORD $0x4ea6d409 // fsub v9.4s, v0.4s, v6.4s
	WORD $0x4e30d572 // fadd v18.4s, v11.4s, v16.4s
	WORD $0x4eb0d573 // fsub v19.4s, v11.4s, v16.4s
	WORD $0xac8148e8 // stp q8, q18, [x7], #0x20
	WORD $0xac814d09 // stp q9, q19, [x8], #0x20
	WORD $0xf100114a // subs x10, x10, #0x4
	WORD $0x54fffcc1 // b.ne <FFTStages+0xe0>
	WORD $0x8b0404c6 // add x6, x6, x4, lsl #1
	WORD $0xeb0100df // cmp x6, x1
	WORD $0x54fffbeb // b.lt <FFTStages+0xd0>
	WORD $0xd37ff884 // lsl x4, x4, #1
	WORD $0x17ffffd9 // b <FFTStages+0xc0>
	RET

// func FFTColsBfly(p, q []complex64, w complex64)
TEXT ·FFTColsBfly(SB), NOSPLIT, $0-56
	MOVD  p_base+0(FP), R0
	MOVD  p_len+8(FP), R1
	MOVD  q_base+24(FP), R2
	FMOVS w_real+48(FP), F0
	FMOVS w_imag+52(FP), F1
	WORD $0x4e04041b // dup v27.4s, v0.s[0]
	WORD $0x4e04043c // dup v28.4s, v1.s[0]
	WORD $0x52b00009 // mov w9, #-0x80000000
	WORD $0x4e080d3a // dup v26.2d, x9
	WORD $0x927ef423 // and x3, x1, #0xfffffffffffffffc
	WORD $0x8b030c09 // add x9, x0, x3, lsl #3
	WORD $0x927ff824 // and x4, x1, #0xfffffffffffffffe
	WORD $0x8b040c0d // add x13, x0, x4, lsl #3
	WORD $0x8b010c0a // add x10, x0, x1, lsl #3
	WORD $0xaa0003eb // mov x11, x0
	WORD $0xaa0203ec // mov x12, x2
	WORD $0xeb09017f // cmp x11, x9
	WORD $0x5400028a // b.ge <FFTColsBfly+0x80>
	WORD $0xad402981 // ldp q1, q10, [x12]
	WORD $0x4ea00825 // rev64 v5.4s, v1.4s
	WORD $0x6e3bdc26 // fmul v6.4s, v1.4s, v27.4s
	WORD $0x6e3cdca7 // fmul v7.4s, v5.4s, v28.4s
	WORD $0x6e3a1ce7 // eor v7.16b, v7.16b, v26.16b
	WORD $0x4e27d4c6 // fadd v6.4s, v6.4s, v7.4s
	WORD $0x4ea0094f // rev64 v15.4s, v10.4s
	WORD $0x6e3bdd50 // fmul v16.4s, v10.4s, v27.4s
	WORD $0x6e3cddf1 // fmul v17.4s, v15.4s, v28.4s
	WORD $0x6e3a1e31 // eor v17.16b, v17.16b, v26.16b
	WORD $0x4e31d610 // fadd v16.4s, v16.4s, v17.4s
	WORD $0xad402d60 // ldp q0, q11, [x11]
	WORD $0x4e26d408 // fadd v8.4s, v0.4s, v6.4s
	WORD $0x4ea6d409 // fsub v9.4s, v0.4s, v6.4s
	WORD $0x4e30d572 // fadd v18.4s, v11.4s, v16.4s
	WORD $0x4eb0d573 // fsub v19.4s, v11.4s, v16.4s
	WORD $0xac814968 // stp q8, q18, [x11], #0x20
	WORD $0xac814d89 // stp q9, q19, [x12], #0x20
	WORD $0x17ffffec // b <FFTColsBfly+0x2c>
	WORD $0xeb0d017f // cmp x11, x13
	WORD $0x5400018a // b.ge <FFTColsBfly+0xb4>
	WORD $0x3dc00181 // ldr q1, [x12]
	WORD $0x4ea00825 // rev64 v5.4s, v1.4s
	WORD $0x6e3bdc26 // fmul v6.4s, v1.4s, v27.4s
	WORD $0x6e3cdca7 // fmul v7.4s, v5.4s, v28.4s
	WORD $0x6e3a1ce7 // eor v7.16b, v7.16b, v26.16b
	WORD $0x4e27d4c6 // fadd v6.4s, v6.4s, v7.4s
	WORD $0x3dc00160 // ldr q0, [x11]
	WORD $0x4e26d408 // fadd v8.4s, v0.4s, v6.4s
	WORD $0x4ea6d409 // fsub v9.4s, v0.4s, v6.4s
	WORD $0x3c810568 // str q8, [x11], #0x10
	WORD $0x3c810589 // str q9, [x12], #0x10
	WORD $0xeb0a017f // cmp x11, x10
	WORD $0x540001aa // b.ge <FFTColsBfly+0xec>
	WORD $0xfd400181 // ldr d1, [x12]
	WORD $0x0ea00825 // rev64 v5.2s, v1.2s
	WORD $0x2e3bdc26 // fmul v6.2s, v1.2s, v27.2s
	WORD $0x2e3cdca7 // fmul v7.2s, v5.2s, v28.2s
	WORD $0x2e3a1ce7 // eor v7.8b, v7.8b, v26.8b
	WORD $0x0e27d4c6 // fadd v6.2s, v6.2s, v7.2s
	WORD $0xfd400160 // ldr d0, [x11]
	WORD $0x0e26d408 // fadd v8.2s, v0.2s, v6.2s
	WORD $0x0ea6d409 // fsub v9.2s, v0.2s, v6.2s
	WORD $0xfc008568 // str d8, [x11], #0x8
	WORD $0xfc008589 // str d9, [x12], #0x8
	WORD $0x17fffff3 // b <FFTColsBfly+0xb4>
	RET

// func FFTCols4(r0, r1, r2, r3 []complex64, w1, w2a, w2b complex64)
TEXT ·FFTCols4(SB), NOSPLIT, $0-120
	MOVD  r0_base+0(FP), R0
	MOVD  r1_base+24(FP), R1
	MOVD  r2_base+48(FP), R2
	MOVD  r3_base+72(FP), R3
	MOVD  r0_len+8(FP), R4
	FMOVS w1_real+96(FP), F0
	FMOVS w1_imag+100(FP), F1
	FMOVS w2a_real+104(FP), F2
	FMOVS w2a_imag+108(FP), F3
	FMOVS w2b_real+112(FP), F4
	FMOVS w2b_imag+116(FP), F5
	WORD $0x4e040414 // dup v20.4s, v0.s[0]
	WORD $0x4e040435 // dup v21.4s, v1.s[0]
	WORD $0x4e040456 // dup v22.4s, v2.s[0]
	WORD $0x4e040477 // dup v23.4s, v3.s[0]
	WORD $0x4e040498 // dup v24.4s, v4.s[0]
	WORD $0x4e0404b9 // dup v25.4s, v5.s[0]
	WORD $0x52b00009 // mov w9, #-0x80000000
	WORD $0x4e080d3a // dup v26.2d, x9
	WORD $0x927ef485 // and x5, x4, #0xfffffffffffffffc
	WORD $0x8b050c06 // add x6, x0, x5, lsl #3
	WORD $0x927ff888 // and x8, x4, #0xfffffffffffffffe
	WORD $0x8b080c0a // add x10, x0, x8, lsl #3
	WORD $0x8b040c07 // add x7, x0, x4, lsl #3
	WORD $0xeb06001f // cmp x0, x6
	WORD $0x5400084a // b.ge <FFTCols4+0x140>
	WORD $0xad402801 // ldp q1, q10, [x0]
	WORD $0xad402c22 // ldp q2, q11, [x1]
	WORD $0xad403443 // ldp q3, q13, [x2]
	WORD $0xad403864 // ldp q4, q14, [x3]
	WORD $0x4ea00845 // rev64 v5.4s, v2.4s
	WORD $0x6e34dc46 // fmul v6.4s, v2.4s, v20.4s
	WORD $0x6e35dca7 // fmul v7.4s, v5.4s, v21.4s
	WORD $0x6e3a1ce7 // eor v7.16b, v7.16b, v26.16b
	WORD $0x4e27d4c6 // fadd v6.4s, v6.4s, v7.4s
	WORD $0x4e26d428 // fadd v8.4s, v1.4s, v6.4s
	WORD $0x4ea6d422 // fsub v2.4s, v1.4s, v6.4s
	WORD $0x4ea0096f // rev64 v15.4s, v11.4s
	WORD $0x6e34dd70 // fmul v16.4s, v11.4s, v20.4s
	WORD $0x6e35ddf1 // fmul v17.4s, v15.4s, v21.4s
	WORD $0x6e3a1e31 // eor v17.16b, v17.16b, v26.16b
	WORD $0x4e31d610 // fadd v16.4s, v16.4s, v17.4s
	WORD $0x4e30d552 // fadd v18.4s, v10.4s, v16.4s
	WORD $0x4eb0d54b // fsub v11.4s, v10.4s, v16.4s
	WORD $0x4ea00885 // rev64 v5.4s, v4.4s
	WORD $0x6e34dc86 // fmul v6.4s, v4.4s, v20.4s
	WORD $0x6e35dca7 // fmul v7.4s, v5.4s, v21.4s
	WORD $0x6e3a1ce7 // eor v7.16b, v7.16b, v26.16b
	WORD $0x4e27d4c6 // fadd v6.4s, v6.4s, v7.4s
	WORD $0x4e26d469 // fadd v9.4s, v3.4s, v6.4s
	WORD $0x4ea6d464 // fsub v4.4s, v3.4s, v6.4s
	WORD $0x4ea009cf // rev64 v15.4s, v14.4s
	WORD $0x6e34ddd0 // fmul v16.4s, v14.4s, v20.4s
	WORD $0x6e35ddf1 // fmul v17.4s, v15.4s, v21.4s
	WORD $0x6e3a1e31 // eor v17.16b, v17.16b, v26.16b
	WORD $0x4e31d610 // fadd v16.4s, v16.4s, v17.4s
	WORD $0x4e30d5b3 // fadd v19.4s, v13.4s, v16.4s
	WORD $0x4eb0d5ae // fsub v14.4s, v13.4s, v16.4s
	WORD $0x4ea00925 // rev64 v5.4s, v9.4s
	WORD $0x6e36dd26 // fmul v6.4s, v9.4s, v22.4s
	WORD $0x6e37dca7 // fmul v7.4s, v5.4s, v23.4s
	WORD $0x6e3a1ce7 // eor v7.16b, v7.16b, v26.16b
	WORD $0x4e27d4c6 // fadd v6.4s, v6.4s, v7.4s
	WORD $0x4e26d501 // fadd v1.4s, v8.4s, v6.4s
	WORD $0x4ea6d503 // fsub v3.4s, v8.4s, v6.4s
	WORD $0x4ea00a6f // rev64 v15.4s, v19.4s
	WORD $0x6e36de70 // fmul v16.4s, v19.4s, v22.4s
	WORD $0x6e37ddf1 // fmul v17.4s, v15.4s, v23.4s
	WORD $0x6e3a1e31 // eor v17.16b, v17.16b, v26.16b
	WORD $0x4e31d610 // fadd v16.4s, v16.4s, v17.4s
	WORD $0x4e30d64a // fadd v10.4s, v18.4s, v16.4s
	WORD $0x4eb0d64d // fsub v13.4s, v18.4s, v16.4s
	WORD $0x4ea00885 // rev64 v5.4s, v4.4s
	WORD $0x6e38dc86 // fmul v6.4s, v4.4s, v24.4s
	WORD $0x6e39dca7 // fmul v7.4s, v5.4s, v25.4s
	WORD $0x6e3a1ce7 // eor v7.16b, v7.16b, v26.16b
	WORD $0x4e27d4c6 // fadd v6.4s, v6.4s, v7.4s
	WORD $0x4e26d448 // fadd v8.4s, v2.4s, v6.4s
	WORD $0x4ea6d444 // fsub v4.4s, v2.4s, v6.4s
	WORD $0x4ea009cf // rev64 v15.4s, v14.4s
	WORD $0x6e38ddd0 // fmul v16.4s, v14.4s, v24.4s
	WORD $0x6e39ddf1 // fmul v17.4s, v15.4s, v25.4s
	WORD $0x6e3a1e31 // eor v17.16b, v17.16b, v26.16b
	WORD $0x4e31d610 // fadd v16.4s, v16.4s, v17.4s
	WORD $0x4e30d572 // fadd v18.4s, v11.4s, v16.4s
	WORD $0x4eb0d56e // fsub v14.4s, v11.4s, v16.4s
	WORD $0xac812801 // stp q1, q10, [x0], #0x20
	WORD $0xac814828 // stp q8, q18, [x1], #0x20
	WORD $0xac813443 // stp q3, q13, [x2], #0x20
	WORD $0xac813864 // stp q4, q14, [x3], #0x20
	WORD $0x17ffffbe // b <FFTCols4+0x34>
	WORD $0xeb0a001f // cmp x0, x10
	WORD $0x540004aa // b.ge <FFTCols4+0x1d8>
	WORD $0x3dc00001 // ldr q1, [x0]
	WORD $0x3dc00022 // ldr q2, [x1]
	WORD $0x3dc00043 // ldr q3, [x2]
	WORD $0x3dc00064 // ldr q4, [x3]
	WORD $0x4ea00845 // rev64 v5.4s, v2.4s
	WORD $0x6e34dc46 // fmul v6.4s, v2.4s, v20.4s
	WORD $0x6e35dca7 // fmul v7.4s, v5.4s, v21.4s
	WORD $0x6e3a1ce7 // eor v7.16b, v7.16b, v26.16b
	WORD $0x4e27d4c6 // fadd v6.4s, v6.4s, v7.4s
	WORD $0x4e26d428 // fadd v8.4s, v1.4s, v6.4s
	WORD $0x4ea6d422 // fsub v2.4s, v1.4s, v6.4s
	WORD $0x4ea00885 // rev64 v5.4s, v4.4s
	WORD $0x6e34dc86 // fmul v6.4s, v4.4s, v20.4s
	WORD $0x6e35dca7 // fmul v7.4s, v5.4s, v21.4s
	WORD $0x6e3a1ce7 // eor v7.16b, v7.16b, v26.16b
	WORD $0x4e27d4c6 // fadd v6.4s, v6.4s, v7.4s
	WORD $0x4e26d469 // fadd v9.4s, v3.4s, v6.4s
	WORD $0x4ea6d464 // fsub v4.4s, v3.4s, v6.4s
	WORD $0x4ea00925 // rev64 v5.4s, v9.4s
	WORD $0x6e36dd26 // fmul v6.4s, v9.4s, v22.4s
	WORD $0x6e37dca7 // fmul v7.4s, v5.4s, v23.4s
	WORD $0x6e3a1ce7 // eor v7.16b, v7.16b, v26.16b
	WORD $0x4e27d4c6 // fadd v6.4s, v6.4s, v7.4s
	WORD $0x4e26d501 // fadd v1.4s, v8.4s, v6.4s
	WORD $0x4ea6d503 // fsub v3.4s, v8.4s, v6.4s
	WORD $0x4ea00885 // rev64 v5.4s, v4.4s
	WORD $0x6e38dc86 // fmul v6.4s, v4.4s, v24.4s
	WORD $0x6e39dca7 // fmul v7.4s, v5.4s, v25.4s
	WORD $0x6e3a1ce7 // eor v7.16b, v7.16b, v26.16b
	WORD $0x4e27d4c6 // fadd v6.4s, v6.4s, v7.4s
	WORD $0x4e26d448 // fadd v8.4s, v2.4s, v6.4s
	WORD $0x4ea6d444 // fsub v4.4s, v2.4s, v6.4s
	WORD $0x3c810401 // str q1, [x0], #0x10
	WORD $0x3c810428 // str q8, [x1], #0x10
	WORD $0x3c810443 // str q3, [x2], #0x10
	WORD $0x3c810464 // str q4, [x3], #0x10
	WORD $0xeb07001f // cmp x0, x7
	WORD $0x540004ca // b.ge <FFTCols4+0x274>
	WORD $0xfd400001 // ldr d1, [x0]
	WORD $0xfd400022 // ldr d2, [x1]
	WORD $0xfd400043 // ldr d3, [x2]
	WORD $0xfd400064 // ldr d4, [x3]
	WORD $0x0ea00845 // rev64 v5.2s, v2.2s
	WORD $0x2e34dc46 // fmul v6.2s, v2.2s, v20.2s
	WORD $0x2e35dca7 // fmul v7.2s, v5.2s, v21.2s
	WORD $0x2e3a1ce7 // eor v7.8b, v7.8b, v26.8b
	WORD $0x0e27d4c6 // fadd v6.2s, v6.2s, v7.2s
	WORD $0x0e26d428 // fadd v8.2s, v1.2s, v6.2s
	WORD $0x0ea6d422 // fsub v2.2s, v1.2s, v6.2s
	WORD $0x0ea00885 // rev64 v5.2s, v4.2s
	WORD $0x2e34dc86 // fmul v6.2s, v4.2s, v20.2s
	WORD $0x2e35dca7 // fmul v7.2s, v5.2s, v21.2s
	WORD $0x2e3a1ce7 // eor v7.8b, v7.8b, v26.8b
	WORD $0x0e27d4c6 // fadd v6.2s, v6.2s, v7.2s
	WORD $0x0e26d469 // fadd v9.2s, v3.2s, v6.2s
	WORD $0x0ea6d464 // fsub v4.2s, v3.2s, v6.2s
	WORD $0x0ea00925 // rev64 v5.2s, v9.2s
	WORD $0x2e36dd26 // fmul v6.2s, v9.2s, v22.2s
	WORD $0x2e37dca7 // fmul v7.2s, v5.2s, v23.2s
	WORD $0x2e3a1ce7 // eor v7.8b, v7.8b, v26.8b
	WORD $0x0e27d4c6 // fadd v6.2s, v6.2s, v7.2s
	WORD $0x0e26d501 // fadd v1.2s, v8.2s, v6.2s
	WORD $0x0ea6d503 // fsub v3.2s, v8.2s, v6.2s
	WORD $0x0ea00885 // rev64 v5.2s, v4.2s
	WORD $0x2e38dc86 // fmul v6.2s, v4.2s, v24.2s
	WORD $0x2e39dca7 // fmul v7.2s, v5.2s, v25.2s
	WORD $0x2e3a1ce7 // eor v7.8b, v7.8b, v26.8b
	WORD $0x0e27d4c6 // fadd v6.2s, v6.2s, v7.2s
	WORD $0x0e26d448 // fadd v8.2s, v2.2s, v6.2s
	WORD $0x0ea6d444 // fsub v4.2s, v2.2s, v6.2s
	WORD $0xfc008401 // str d1, [x0], #0x8
	WORD $0xfc008428 // str d8, [x1], #0x8
	WORD $0xfc008443 // str d3, [x2], #0x8
	WORD $0xfc008464 // str d4, [x3], #0x8
	WORD $0x17ffffda // b <FFTCols4+0x1d8>
	RET

// func MulConj(spec, tspec []complex64)
TEXT ·MulConj(SB), NOSPLIT, $0-48
	MOVD spec_base+0(FP), R0
	MOVD spec_len+8(FP), R1
	MOVD tspec_base+24(FP), R2
	WORD $0xd2f00009 // mov x9, #-0x8000000000000000
	WORD $0x4e080d3a // dup v26.2d, x9
	WORD $0x927ef423 // and x3, x1, #0xfffffffffffffffc
	WORD $0x8b030c09 // add x9, x0, x3, lsl #3
	WORD $0x927ff824 // and x4, x1, #0xfffffffffffffffe
	WORD $0x8b040c0d // add x13, x0, x4, lsl #3
	WORD $0x8b010c0a // add x10, x0, x1, lsl #3
	WORD $0xaa0003eb // mov x11, x0
	WORD $0xaa0203ec // mov x12, x2
	WORD $0xeb09017f // cmp x11, x9
	WORD $0x5400026a // b.ge <MulConj+0x74>
	WORD $0xad402961 // ldp q1, q10, [x11]
	WORD $0xacc13182 // ldp q2, q12, [x12], #0x20
	WORD $0x4e822843 // trn1 v3.4s, v2.4s, v2.4s
	WORD $0x4e826844 // trn2 v4.4s, v2.4s, v2.4s
	WORD $0x4ea00825 // rev64 v5.4s, v1.4s
	WORD $0x6e23dc26 // fmul v6.4s, v1.4s, v3.4s
	WORD $0x6e24dca7 // fmul v7.4s, v5.4s, v4.4s
	WORD $0x6e3a1ce7 // eor v7.16b, v7.16b, v26.16b
	WORD $0x4e27d4c6 // fadd v6.4s, v6.4s, v7.4s
	WORD $0x4e8c298d // trn1 v13.4s, v12.4s, v12.4s
	WORD $0x4e8c698e // trn2 v14.4s, v12.4s, v12.4s
	WORD $0x4ea0094f // rev64 v15.4s, v10.4s
	WORD $0x6e2ddd50 // fmul v16.4s, v10.4s, v13.4s
	WORD $0x6e2eddf1 // fmul v17.4s, v15.4s, v14.4s
	WORD $0x6e3a1e31 // eor v17.16b, v17.16b, v26.16b
	WORD $0x4e31d610 // fadd v16.4s, v16.4s, v17.4s
	WORD $0xac814166 // stp q6, q16, [x11], #0x20
	WORD $0x17ffffed // b <MulConj+0x24>
	WORD $0xeb0d017f // cmp x11, x13
	WORD $0x5400016a // b.ge <MulConj+0xa4>
	WORD $0x3dc00161 // ldr q1, [x11]
	WORD $0x3cc10582 // ldr q2, [x12], #0x10
	WORD $0x4e822843 // trn1 v3.4s, v2.4s, v2.4s
	WORD $0x4e826844 // trn2 v4.4s, v2.4s, v2.4s
	WORD $0x4ea00825 // rev64 v5.4s, v1.4s
	WORD $0x6e23dc26 // fmul v6.4s, v1.4s, v3.4s
	WORD $0x6e24dca7 // fmul v7.4s, v5.4s, v4.4s
	WORD $0x6e3a1ce7 // eor v7.16b, v7.16b, v26.16b
	WORD $0x4e27d4c6 // fadd v6.4s, v6.4s, v7.4s
	WORD $0x3c810566 // str q6, [x11], #0x10
	WORD $0xeb0a017f // cmp x11, x10
	WORD $0x5400018a // b.ge <MulConj+0xd8>
	WORD $0xfd400161 // ldr d1, [x11]
	WORD $0xfc408582 // ldr d2, [x12], #0x8
	WORD $0x0e822843 // trn1 v3.2s, v2.2s, v2.2s
	WORD $0x0e826844 // trn2 v4.2s, v2.2s, v2.2s
	WORD $0x0ea00825 // rev64 v5.2s, v1.2s
	WORD $0x2e23dc26 // fmul v6.2s, v1.2s, v3.2s
	WORD $0x2e24dca7 // fmul v7.2s, v5.2s, v4.2s
	WORD $0x2e3a1ce7 // eor v7.8b, v7.8b, v26.8b
	WORD $0x0e27d4c6 // fadd v6.2s, v6.2s, v7.2s
	WORD $0xfc008566 // str d6, [x11], #0x8
	WORD $0x17fffff4 // b <MulConj+0xa4>
	RET

// func NormRow(rrow []float32, crow []float32, wt *float64, stride, n, cn int,
//	mean *[4]float64, invArea, eps, templNorm float64)
TEXT ·NormRow(SB), NOSPLIT, $0-112
	MOVD  rrow_base+0(FP), R0
	MOVD  crow_base+24(FP), R1
	MOVD  wt+48(FP), R2
	MOVD  stride+56(FP), R3
	MOVD  n+64(FP), R4
	MOVD  cn+72(FP), R5
	MOVD  mean+80(FP), R6
	FMOVD invArea+88(FP), F0
	FMOVD eps+96(FP), F1
	FMOVD templNorm+104(FP), F2
	WORD $0x4e08041c // dup v28.2d, v0.d[0]
	WORD $0x4e08043d // dup v29.2d, v1.d[0]
	WORD $0x4e08045e // dup v30.2d, v2.d[0]
	WORD $0x6f03f41b // fmov v27.2d, #0.50000000
	WORD $0x6f03f619 // fmov v25.2d, #1.00000000
	WORD $0x6f03f658 // fmov v24.2d, #1.12500000
	WORD $0xd2f00009 // mov x9, #-0x8000000000000000
	WORD $0x4e080d37 // dup v23.2d, x9
	WORD $0x6f00e416 // movi v22.2d, #0000000000000000
	WORD $0xd37df067 // lsl x7, x3, #3
	WORD $0xd2800008 // mov x8, #0x0
	WORD $0x3cc10423 // ldr q3, [x1], #0x10
	WORD $0x4e61786d // fcvtl2 v13.2d, v3.4s
	WORD $0x0e617863 // fcvtl v3.2d, v3.2s
	WORD $0x6f00e404 // movi v4.2d, #0000000000000000
	WORD $0x6f00e40e // movi v14.2d, #0000000000000000
	WORD $0x8b080c49 // add x9, x2, x8, lsl #3
	WORD $0xaa0503ea // mov x10, x5
	WORD $0xaa0603eb // mov x11, x6
	WORD $0xad403d25 // ldp q5, q15, [x9]
	WORD $0x8b070129 // add x9, x9, x7
	WORD $0xfc408567 // ldr d7, [x11], #0x8
	WORD $0x4e0804e7 // dup v7.2d, v7.d[0]
	WORD $0x6e65dca6 // fmul v6.2d, v5.2d, v5.2d
	WORD $0x4e66d484 // fadd v4.2d, v4.2d, v6.2d
	WORD $0x6e6fddf0 // fmul v16.2d, v15.2d, v15.2d
	WORD $0x4e70d5ce // fadd v14.2d, v14.2d, v16.2d
	WORD $0x6e67dca6 // fmul v6.2d, v5.2d, v7.2d
	WORD $0x4ee6d463 // fsub v3.2d, v3.2d, v6.2d
	WORD $0x6e67ddf0 // fmul v16.2d, v15.2d, v7.2d
	WORD $0x4ef0d5ad // fsub v13.2d, v13.2d, v16.2d
	WORD $0xf100054a // subs x10, x10, #0x1
	WORD $0x54fffe61 // b.ne <NormRow+0x4c>
	WORD $0xad404928 // ldp q8, q18, [x9]
	WORD $0x6e7cdc84 // fmul v4.2d, v4.2d, v28.2d
	WORD $0x6e7cddce // fmul v14.2d, v14.2d, v28.2d
	WORD $0x4ee4d505 // fsub v5.2d, v8.2d, v4.2d
	WORD $0x4eeed64f // fsub v15.2d, v18.2d, v14.2d
	WORD $0x4e76f4a5 // fmax v5.2d, v5.2d, v22.2d
	WORD $0x4e76f5ef // fmax v15.2d, v15.2d, v22.2d
	WORD $0x6e7ddd06 // fmul v6.2d, v8.2d, v29.2d
	WORD $0x6e7dde50 // fmul v16.2d, v18.2d, v29.2d
	WORD $0x4efbf4c6 // fmin v6.2d, v6.2d, v27.2d
	WORD $0x4efbf610 // fmin v16.2d, v16.2d, v27.2d
	WORD $0x6ee1f8a7 // fsqrt v7.2d, v5.2d
	WORD $0x6ee1f9f1 // fsqrt v17.2d, v15.2d
	WORD $0x6e7edce7 // fmul v7.2d, v7.2d, v30.2d
	WORD $0x6e7ede31 // fmul v17.2d, v17.2d, v30.2d
	WORD $0x6ee6e4a9 // fcmgt v9.2d, v5.2d, v6.2d
	WORD $0x6ef0e5f3 // fcmgt v19.2d, v15.2d, v16.2d
	WORD $0x4e291ce7 // and v7.16b, v7.16b, v9.16b
	WORD $0x4e331e31 // and v17.16b, v17.16b, v19.16b
	WORD $0x4ee0f86a // fabs v10.2d, v3.2d
	WORD $0x4ee0f9b4 // fabs v20.2d, v13.2d
	WORD $0x6eeae4eb // fcmgt v11.2d, v7.2d, v10.2d
	WORD $0x6ef4e635 // fcmgt v21.2d, v17.2d, v20.2d
	WORD $0x4eab1d6c // mov v12.16b, v11.16b
	WORD $0x6e791cec // bsl v12.16b, v7.16b, v25.16b
	WORD $0x4e2b1c65 // and v5.16b, v3.16b, v11.16b
	WORD $0x6e6cfca5 // fdiv v5.2d, v5.2d, v12.2d
	WORD $0x4eb51eac // mov v12.16b, v21.16b
	WORD $0x6e791e2c // bsl v12.16b, v17.16b, v25.16b
	WORD $0x4e351daf // and v15.16b, v13.16b, v21.16b
	WORD $0x6e6cfdef // fdiv v15.2d, v15.2d, v12.2d
	WORD $0x6e78dce6 // fmul v6.2d, v7.2d, v24.2d
	WORD $0x6eeae4c6 // fcmgt v6.2d, v6.2d, v10.2d
	WORD $0x6e78de30 // fmul v16.2d, v17.2d, v24.2d
	WORD $0x6ef4e610 // fcmgt v16.2d, v16.2d, v20.2d
	WORD $0x4e371c68 // and v8.16b, v3.16b, v23.16b
	WORD $0x4eb91d08 // orr v8.16b, v8.16b, v25.16b
	WORD $0x4e261d08 // and v8.16b, v8.16b, v6.16b
	WORD $0x4e371db2 // and v18.16b, v13.16b, v23.16b
	WORD $0x4eb91e52 // orr v18.16b, v18.16b, v25.16b
	WORD $0x4e301e52 // and v18.16b, v18.16b, v16.16b
	WORD $0x4eab1d69 // mov v9.16b, v11.16b
	WORD $0x6e681ca9 // bsl v9.16b, v5.16b, v8.16b
	WORD $0x4eb51eb3 // mov v19.16b, v21.16b
	WORD $0x6e721df3 // bsl v19.16b, v15.16b, v18.16b
	WORD $0x0e616929 // fcvtn v9.2s, v9.2d
	WORD $0x4e616a69 // fcvtn2 v9.4s, v19.2d
	WORD $0x3c810409 // str q9, [x0], #0x10
	WORD $0x91001108 // add x8, x8, #0x4
	WORD $0xeb04011f // cmp x8, x4
	WORD $0x54fff70b // b.lt <NormRow+0x2c>
	RET

// func PackRows2(z []complex64, ra, rb []uint8, step int)
TEXT ·PackRows2(SB), NOSPLIT, $0-80
	MOVD z_base+0(FP), R0
	MOVD z_len+8(FP), R1
	MOVD ra_base+24(FP), R2
	MOVD ra_len+32(FP), R3
	MOVD rb_base+48(FP), R4
	MOVD rb_len+56(FP), R5
	MOVD step+72(FP), R6
	WORD $0x927ef427 // and x7, x1, #0xfffffffffffffffc
	WORD $0xf10010df // cmp x6, #0x4
	WORD $0x54000040 // b.eq <PackRows2+0x10>
	WORD $0x1400002a // b <PackRows2+0xb4>
	WORD $0xd344fc68 // lsr x8, x3, #4
	WORD $0xd37ef508 // lsl x8, x8, #2
	WORD $0xeb07011f // cmp x8, x7
	WORD $0x9a87b107 // csel x7, x8, x7, lt
	WORD $0xd344fca8 // lsr x8, x5, #4
	WORD $0xd37ef508 // lsl x8, x8, #2
	WORD $0xeb07011f // cmp x8, x7
	WORD $0x9a87b107 // csel x7, x8, x7, lt
	WORD $0x4f07e7ff // movi v31.16b, #0xff
	WORD $0x52808009 // mov w9, #0x400
	WORD $0x72a18109 // movk w9, #0xc08, lsl #16
	WORD $0x4e041d3f // mov v31.s[0], w9
	WORD $0xd2800009 // mov x9, #0x0
	WORD $0xeb07013f // cmp x9, x7
	WORD $0x5400020a // b.ge <PackRows2+0x88>
	WORD $0x3cc10441 // ldr q1, [x2], #0x10
	WORD $0x3cc10482 // ldr q2, [x4], #0x10
	WORD $0x0e1f0021 // tbl v1.8b, { v1.16b }, v31.8b
	WORD $0x0e1f0042 // tbl v2.8b, { v2.16b }, v31.8b
	WORD $0x2f08a421 // ushll v1.8h, v1.8b, #0x0
	WORD $0x2f08a442 // ushll v2.8h, v2.8b, #0x0
	WORD $0x2f10a421 // ushll v1.4s, v1.4h, #0x0
	WORD $0x2f10a442 // ushll v2.4s, v2.4h, #0x0
	WORD $0x6e21d821 // ucvtf v1.4s, v1.4s
	WORD $0x6e21d842 // ucvtf v2.4s, v2.4s
	WORD $0x4e823823 // zip1 v3.4s, v1.4s, v2.4s
	WORD $0x4e827824 // zip2 v4.4s, v1.4s, v2.4s
	WORD $0xac811003 // stp q3, q4, [x0], #0x20
	WORD $0x91001129 // add x9, x9, #0x4
	WORD $0x17fffff0 // b <PackRows2+0x44>
	WORD $0xeb01013f // cmp x9, x1
	WORD $0x540004aa // b.ge <PackRows2+0x120>
	WORD $0x3840444a // ldrb w10, [x2], #0x4
	WORD $0x3840448b // ldrb w11, [x4], #0x4
	WORD $0x1e230141 // ucvtf s1, w10
	WORD $0x1e230162 // ucvtf s2, w11
	WORD $0xbd000001 // str s1, [x0]
	WORD $0xbd000402 // str s2, [x0, #0x4]
	WORD $0x91002000 // add x0, x0, #0x8
	WORD $0x91000529 // add x9, x9, #0x1
	WORD $0x17fffff6 // b <PackRows2+0x88>
	WORD $0xd2800009 // mov x9, #0x0
	WORD $0xeb07013f // cmp x9, x7
	WORD $0x540001ca // b.ge <PackRows2+0xf4>
	WORD $0xbc404441 // ldr s1, [x2], #0x4
	WORD $0xbc404482 // ldr s2, [x4], #0x4
	WORD $0x2f08a421 // ushll v1.8h, v1.8b, #0x0
	WORD $0x2f08a442 // ushll v2.8h, v2.8b, #0x0
	WORD $0x2f10a421 // ushll v1.4s, v1.4h, #0x0
	WORD $0x2f10a442 // ushll v2.4s, v2.4h, #0x0
	WORD $0x6e21d821 // ucvtf v1.4s, v1.4s
	WORD $0x6e21d842 // ucvtf v2.4s, v2.4s
	WORD $0x4e823823 // zip1 v3.4s, v1.4s, v2.4s
	WORD $0x4e827824 // zip2 v4.4s, v1.4s, v2.4s
	WORD $0xac811003 // stp q3, q4, [x0], #0x20
	WORD $0x91001129 // add x9, x9, #0x4
	WORD $0x17fffff2 // b <PackRows2+0xb8>
	WORD $0xeb01013f // cmp x9, x1
	WORD $0x5400014a // b.ge <PackRows2+0x120>
	WORD $0x3840144a // ldrb w10, [x2], #0x1
	WORD $0x3840148b // ldrb w11, [x4], #0x1
	WORD $0x1e230141 // ucvtf s1, w10
	WORD $0x1e230162 // ucvtf s2, w11
	WORD $0xbd000001 // str s1, [x0]
	WORD $0xbd000402 // str s2, [x0, #0x4]
	WORD $0x91002000 // add x0, x0, #0x8
	WORD $0x91000529 // add x9, x9, #0x1
	WORD $0x17fffff6 // b <PackRows2+0xf4>
	RET

// func PackRows1(z []complex64, ra []uint8, step int)
TEXT ·PackRows1(SB), NOSPLIT, $0-56
	MOVD z_base+0(FP), R0
	MOVD z_len+8(FP), R1
	MOVD ra_base+24(FP), R2
	MOVD ra_len+32(FP), R3
	MOVD step+48(FP), R4
	WORD $0x927ef427 // and x7, x1, #0xfffffffffffffffc
	WORD $0x4f000402 // movi v2.4s, #0x0
	WORD $0xf100109f // cmp x4, #0x4
	WORD $0x54000040 // b.eq <PackRows1+0x14>
	WORD $0x1400001f // b <PackRows1+0x8c>
	WORD $0xd344fc68 // lsr x8, x3, #4
	WORD $0xd37ef508 // lsl x8, x8, #2
	WORD $0xeb07011f // cmp x8, x7
	WORD $0x9a87b107 // csel x7, x8, x7, lt
	WORD $0x4f07e7ff // movi v31.16b, #0xff
	WORD $0x52808009 // mov w9, #0x400
	WORD $0x72a18109 // movk w9, #0xc08, lsl #16
	WORD $0x4e041d3f // mov v31.s[0], w9
	WORD $0xd2800009 // mov x9, #0x0
	WORD $0xeb07013f // cmp x9, x7
	WORD $0x5400016a // b.ge <PackRows1+0x68>
	WORD $0x3cc10441 // ldr q1, [x2], #0x10
	WORD $0x0e1f0021 // tbl v1.8b, { v1.16b }, v31.8b
	WORD $0x2f08a421 // ushll v1.8h, v1.8b, #0x0
	WORD $0x2f10a421 // ushll v1.4s, v1.4h, #0x0
	WORD $0x6e21d821 // ucvtf v1.4s, v1.4s
	WORD $0x4e823823 // zip1 v3.4s, v1.4s, v2.4s
	WORD $0x4e827824 // zip2 v4.4s, v1.4s, v2.4s
	WORD $0xac811003 // stp q3, q4, [x0], #0x20
	WORD $0x91001129 // add x9, x9, #0x4
	WORD $0x17fffff5 // b <PackRows1+0x38>
	WORD $0xeb01013f // cmp x9, x1
	WORD $0x540003aa // b.ge <PackRows1+0xe0>
	WORD $0x3840444a // ldrb w10, [x2], #0x4
	WORD $0x1e230141 // ucvtf s1, w10
	WORD $0xbd000001 // str s1, [x0]
	WORD $0xb900041f // str wzr, [x0, #0x4]
	WORD $0x91002000 // add x0, x0, #0x8
	WORD $0x91000529 // add x9, x9, #0x1
	WORD $0x17fffff8 // b <PackRows1+0x68>
	WORD $0xd2800009 // mov x9, #0x0
	WORD $0xeb07013f // cmp x9, x7
	WORD $0x5400014a // b.ge <PackRows1+0xbc>
	WORD $0xbc404441 // ldr s1, [x2], #0x4
	WORD $0x2f08a421 // ushll v1.8h, v1.8b, #0x0
	WORD $0x2f10a421 // ushll v1.4s, v1.4h, #0x0
	WORD $0x6e21d821 // ucvtf v1.4s, v1.4s
	WORD $0x4e823823 // zip1 v3.4s, v1.4s, v2.4s
	WORD $0x4e827824 // zip2 v4.4s, v1.4s, v2.4s
	WORD $0xac811003 // stp q3, q4, [x0], #0x20
	WORD $0x91001129 // add x9, x9, #0x4
	WORD $0x17fffff6 // b <PackRows1+0x90>
	WORD $0xeb01013f // cmp x9, x1
	WORD $0x5400010a // b.ge <PackRows1+0xe0>
	WORD $0x3840144a // ldrb w10, [x2], #0x1
	WORD $0x1e230141 // ucvtf s1, w10
	WORD $0xbd000001 // str s1, [x0]
	WORD $0xb900041f // str wzr, [x0, #0x4]
	WORD $0x91002000 // add x0, x0, #0x8
	WORD $0x91000529 // add x9, x9, #0x1
	WORD $0x17fffff8 // b <PackRows1+0xbc>
	RET

// func Untangle(sa, sb, z []complex64, n, k0, k1 int)
TEXT ·Untangle(SB), NOSPLIT, $0-96
	MOVD sa_base+0(FP), R0
	MOVD sb_base+24(FP), R1
	MOVD z_base+48(FP), R2
	MOVD n+72(FP), R3
	MOVD k0+80(FP), R4
	MOVD k1+88(FP), R5
	WORD $0xd2f00009 // mov x9, #-0x8000000000000000
	WORD $0x4e080d3a // dup v26.2d, x9
	WORD $0x4f03f41b // fmov v27.4s, #0.50000000
	WORD $0xcb0400a6 // sub x6, x5, x4
	WORD $0x927ef4cd // and x13, x6, #0xfffffffffffffffc
	WORD $0x8b0401ad // add x13, x13, x4
	WORD $0x927ff8c6 // and x6, x6, #0xfffffffffffffffe
	WORD $0x8b0400c6 // add x6, x6, x4
	WORD $0x8b040c07 // add x7, x0, x4, lsl #3
	WORD $0x8b040c28 // add x8, x1, x4, lsl #3
	WORD $0x8b040c4a // add x10, x2, x4, lsl #3
	WORD $0xcb04006b // sub x11, x3, x4
	WORD $0xd100056b // sub x11, x11, #0x1
	WORD $0x8b0b0c4b // add x11, x2, x11, lsl #3
	WORD $0xaa0403ec // mov x12, x4
	WORD $0xeb0d019f // cmp x12, x13
	WORD $0x5400034a // b.ge <Untangle+0xa8>
	WORD $0xacc12941 // ldp q1, q10, [x10], #0x20
	WORD $0xad7f896c // ldp q12, q2, [x11, #-0x10]
	WORD $0xd100816b // sub x11, x11, #0x20
	WORD $0x6e024042 // ext v2.16b, v2.16b, v2.16b, #0x8
	WORD $0x6e0c418c // ext v12.16b, v12.16b, v12.16b, #0x8
	WORD $0x6e3a1c43 // eor v3.16b, v2.16b, v26.16b
	WORD $0x4e23d423 // fadd v3.4s, v1.4s, v3.4s
	WORD $0x6e3bdc63 // fmul v3.4s, v3.4s, v27.4s
	WORD $0x6e3a1d8d // eor v13.16b, v12.16b, v26.16b
	WORD $0x4e2dd54d // fadd v13.4s, v10.4s, v13.4s
	WORD $0x6e3bddad // fmul v13.4s, v13.4s, v27.4s
	WORD $0xac8134e3 // stp q3, q13, [x7], #0x20
	WORD $0x4ea00824 // rev64 v4.4s, v1.4s
	WORD $0x6e3a1c84 // eor v4.16b, v4.16b, v26.16b
	WORD $0x4ea00845 // rev64 v5.4s, v2.4s
	WORD $0x4e25d484 // fadd v4.4s, v4.4s, v5.4s
	WORD $0x6e3bdc84 // fmul v4.4s, v4.4s, v27.4s
	WORD $0x4ea0094e // rev64 v14.4s, v10.4s
	WORD $0x6e3a1dce // eor v14.16b, v14.16b, v26.16b
	WORD $0x4ea0098f // rev64 v15.4s, v12.4s
	WORD $0x4e2fd5ce // fadd v14.4s, v14.4s, v15.4s
	WORD $0x6e3bddce // fmul v14.4s, v14.4s, v27.4s
	WORD $0xac813904 // stp q4, q14, [x8], #0x20
	WORD $0x9100118c // add x12, x12, #0x4
	WORD $0x17ffffe6 // b <Untangle+0x3c>
	WORD $0xeb06019f // cmp x12, x6
	WORD $0x5400020a // b.ge <Untangle+0xec>
	WORD $0x3cc10541 // ldr q1, [x10], #0x10
	WORD $0x3cdf0562 // ldr q2, [x11], #-0x10
	WORD $0x6e024042 // ext v2.16b, v2.16b, v2.16b, #0x8
	WORD $0x6e3a1c43 // eor v3.16b, v2.16b, v26.16b
	WORD $0x4e23d423 // fadd v3.4s, v1.4s, v3.4s
	WORD $0x6e3bdc63 // fmul v3.4s, v3.4s, v27.4s
	WORD $0x3c8104e3 // str q3, [x7], #0x10
	WORD $0x4ea00824 // rev64 v4.4s, v1.4s
	WORD $0x6e3a1c84 // eor v4.16b, v4.16b, v26.16b
	WORD $0x4ea00845 // rev64 v5.4s, v2.4s
	WORD $0x4e25d484 // fadd v4.4s, v4.4s, v5.4s
	WORD $0x6e3bdc84 // fmul v4.4s, v4.4s, v27.4s
	WORD $0x3c810504 // str q4, [x8], #0x10
	WORD $0x9100098c // add x12, x12, #0x2
	WORD $0x17fffff0 // b <Untangle+0xa8>
	WORD $0xeb05019f // cmp x12, x5
	WORD $0x5400020a // b.ge <Untangle+0x130>
	WORD $0xfc408541 // ldr d1, [x10], #0x8
	WORD $0xcb0c006d // sub x13, x3, x12
	WORD $0xfc6d7842 // ldr d2, [x2, x13, lsl #3]
	WORD $0x2e3a1c43 // eor v3.8b, v2.8b, v26.8b
	WORD $0x0e23d423 // fadd v3.2s, v1.2s, v3.2s
	WORD $0x2e3bdc63 // fmul v3.2s, v3.2s, v27.2s
	WORD $0xfc0084e3 // str d3, [x7], #0x8
	WORD $0x0ea00824 // rev64 v4.2s, v1.2s
	WORD $0x2e3a1c84 // eor v4.8b, v4.8b, v26.8b
	WORD $0x0ea00845 // rev64 v5.2s, v2.2s
	WORD $0x0e25d484 // fadd v4.2s, v4.2s, v5.2s
	WORD $0x2e3bdc84 // fmul v4.2s, v4.2s, v27.2s
	WORD $0xfc008504 // str d4, [x8], #0x8
	WORD $0x9100058c // add x12, x12, #0x1
	WORD $0x17fffff0 // b <Untangle+0xec>
	RET

// func CombineLow(z, sa, sb []complex64)
TEXT ·CombineLow(SB), NOSPLIT, $0-72
	MOVD z_base+0(FP), R0
	MOVD z_len+8(FP), R1
	MOVD sa_base+24(FP), R2
	MOVD sb_base+48(FP), R3
	WORD $0x52b00009 // mov w9, #-0x80000000
	WORD $0x4e080d3a // dup v26.2d, x9
	WORD $0x927ef427 // and x7, x1, #0xfffffffffffffffc
	WORD $0x8b070c08 // add x8, x0, x7, lsl #3
	WORD $0x927ff824 // and x4, x1, #0xfffffffffffffffe
	WORD $0x8b040c05 // add x5, x0, x4, lsl #3
	WORD $0x8b010c06 // add x6, x0, x1, lsl #3
	WORD $0xeb08001f // cmp x0, x8
	WORD $0x5400016a // b.ge <CombineLow+0x4c>
	WORD $0xacc12841 // ldp q1, q10, [x2], #0x20
	WORD $0xacc12c62 // ldp q2, q11, [x3], #0x20
	WORD $0x4ea00842 // rev64 v2.4s, v2.4s
	WORD $0x6e3a1c42 // eor v2.16b, v2.16b, v26.16b
	WORD $0x4e22d421 // fadd v1.4s, v1.4s, v2.4s
	WORD $0x4ea0096b // rev64 v11.4s, v11.4s
	WORD $0x6e3a1d6b // eor v11.16b, v11.16b, v26.16b
	WORD $0x4e2bd54a // fadd v10.4s, v10.4s, v11.4s
	WORD $0xac812801 // stp q1, q10, [x0], #0x20
	WORD $0x17fffff5 // b <CombineLow+0x1c>
	WORD $0xeb05001f // cmp x0, x5
	WORD $0x540000ea // b.ge <CombineLow+0x6c>
	WORD $0x3cc10441 // ldr q1, [x2], #0x10
	WORD $0x3cc10462 // ldr q2, [x3], #0x10
	WORD $0x4ea00842 // rev64 v2.4s, v2.4s
	WORD $0x6e3a1c42 // eor v2.16b, v2.16b, v26.16b
	WORD $0x4e22d421 // fadd v1.4s, v1.4s, v2.4s
	WORD $0x3c810401 // str q1, [x0], #0x10
	WORD $0xeb06001f // cmp x0, x6
	WORD $0x5400010a // b.ge <CombineLow+0x90>
	WORD $0xfc408441 // ldr d1, [x2], #0x8
	WORD $0xfc408462 // ldr d2, [x3], #0x8
	WORD $0x0ea00842 // rev64 v2.2s, v2.2s
	WORD $0x2e3a1c42 // eor v2.8b, v2.8b, v26.8b
	WORD $0x0e22d421 // fadd v1.2s, v1.2s, v2.2s
	WORD $0xfc008401 // str d1, [x0], #0x8
	WORD $0x17fffff8 // b <CombineLow+0x6c>
	RET

// func CombineHigh(z, sa, sb []complex64, n, hw int)
TEXT ·CombineHigh(SB), NOSPLIT, $0-88
	MOVD z_base+0(FP), R0
	MOVD sa_base+24(FP), R1
	MOVD sb_base+48(FP), R2
	MOVD n+72(FP), R3
	MOVD hw+80(FP), R4
	WORD $0xd2f00009 // mov x9, #-0x8000000000000000
	WORD $0x4e080d3a // dup v26.2d, x9
	WORD $0xcb040065 // sub x5, x3, x4
	WORD $0x927ef4ad // and x13, x5, #0xfffffffffffffffc
	WORD $0x8b040c0e // add x14, x0, x4, lsl #3
	WORD $0x8b0d0dce // add x14, x14, x13, lsl #3
	WORD $0x927ff8a6 // and x6, x5, #0xfffffffffffffffe
	WORD $0x8b040c07 // add x7, x0, x4, lsl #3
	WORD $0x8b060ce8 // add x8, x7, x6, lsl #3
	WORD $0x8b030c09 // add x9, x0, x3, lsl #3
	WORD $0xcb04006a // sub x10, x3, x4
	WORD $0xd100054a // sub x10, x10, #0x1
	WORD $0x8b0a0c2b // add x11, x1, x10, lsl #3
	WORD $0x8b0a0c4c // add x12, x2, x10, lsl #3
	WORD $0xeb0e00ff // cmp x7, x14
	WORD $0x5400022a // b.ge <CombineHigh+0x80>
	WORD $0xad7f856a // ldp q10, q1, [x11, #-0x10]
	WORD $0xd100816b // sub x11, x11, #0x20
	WORD $0xad7f898b // ldp q11, q2, [x12, #-0x10]
	WORD $0xd100818c // sub x12, x12, #0x20
	WORD $0x6e014021 // ext v1.16b, v1.16b, v1.16b, #0x8
	WORD $0x6e024042 // ext v2.16b, v2.16b, v2.16b, #0x8
	WORD $0x4ea00842 // rev64 v2.4s, v2.4s
	WORD $0x6e3a1c21 // eor v1.16b, v1.16b, v26.16b
	WORD $0x4e21d441 // fadd v1.4s, v2.4s, v1.4s
	WORD $0x6e0a414a // ext v10.16b, v10.16b, v10.16b, #0x8
	WORD $0x6e0b416b // ext v11.16b, v11.16b, v11.16b, #0x8
	WORD $0x4ea0096b // rev64 v11.4s, v11.4s
	WORD $0x6e3a1d4a // eor v10.16b, v10.16b, v26.16b
	WORD $0x4e2ad56a // fadd v10.4s, v11.4s, v10.4s
	WORD $0xac8128e1 // stp q1, q10, [x7], #0x20
	WORD $0x17ffffef // b <CombineHigh+0x38>
	WORD $0xeb0800ff // cmp x7, x8
	WORD $0x5400014a // b.ge <CombineHigh+0xac>
	WORD $0x3cdf0561 // ldr q1, [x11], #-0x10
	WORD $0x3cdf0582 // ldr q2, [x12], #-0x10
	WORD $0x6e014021 // ext v1.16b, v1.16b, v1.16b, #0x8
	WORD $0x6e024042 // ext v2.16b, v2.16b, v2.16b, #0x8
	WORD $0x4ea00842 // rev64 v2.4s, v2.4s
	WORD $0x6e3a1c21 // eor v1.16b, v1.16b, v26.16b
	WORD $0x4e21d441 // fadd v1.4s, v2.4s, v1.4s
	WORD $0x3c8104e1 // str q1, [x7], #0x10
	WORD $0x17fffff6 // b <CombineHigh+0x80>
	WORD $0xeb0900ff // cmp x7, x9
	WORD $0x5400014a // b.ge <CombineHigh+0xd8>
	WORD $0xcb07012a // sub x10, x9, x7
	WORD $0xd343fd4a // lsr x10, x10, #3
	WORD $0xfc6a7821 // ldr d1, [x1, x10, lsl #3]
	WORD $0xfc6a7842 // ldr d2, [x2, x10, lsl #3]
	WORD $0x0ea00842 // rev64 v2.2s, v2.2s
	WORD $0x2e3a1c21 // eor v1.8b, v1.8b, v26.8b
	WORD $0x0e21d441 // fadd v1.2s, v2.2s, v1.2s
	WORD $0xfc0084e1 // str d1, [x7], #0x8
	WORD $0x17fffff6 // b <CombineHigh+0xac>
	RET

// func EmitRe(dst []float32, z []complex64, add bool)
TEXT ·EmitRe(SB), NOSPLIT, $0-49
	MOVD  dst_base+0(FP), R0
	MOVD  dst_len+8(FP), R1
	MOVD  z_base+24(FP), R2
	MOVBU add+48(FP), R3
	WORD $0x927df027 // and x7, x1, #0xfffffffffffffff8
	WORD $0x8b070808 // add x8, x0, x7, lsl #2
	WORD $0x927ef424 // and x4, x1, #0xfffffffffffffffc
	WORD $0x8b040805 // add x5, x0, x4, lsl #2
	WORD $0x8b010806 // add x6, x0, x1, lsl #2
	WORD $0xeb08001f // cmp x0, x8
	WORD $0x5400016a // b.ge <EmitRe+0x44>
	WORD $0xacc10841 // ldp q1, q2, [x2], #0x20
	WORD $0xacc12c4a // ldp q10, q11, [x2], #0x20
	WORD $0x4e821823 // uzp1 v3.4s, v1.4s, v2.4s
	WORD $0x4e8b194c // uzp1 v12.4s, v10.4s, v11.4s
	WORD $0xb4000083 // cbz x3, <EmitRe+0x3c>
	WORD $0xad402400 // ldp q0, q9, [x0]
	WORD $0x4e23d403 // fadd v3.4s, v0.4s, v3.4s
	WORD $0x4e2cd52c // fadd v12.4s, v9.4s, v12.4s
	WORD $0xac813003 // stp q3, q12, [x0], #0x20
	WORD $0x17fffff5 // b <EmitRe+0x14>
	WORD $0xeb05001f // cmp x0, x5
	WORD $0x540000ea // b.ge <EmitRe+0x64>
	WORD $0xacc10841 // ldp q1, q2, [x2], #0x20
	WORD $0x4e821823 // uzp1 v3.4s, v1.4s, v2.4s
	WORD $0xb4000063 // cbz x3, <EmitRe+0x60>
	WORD $0x3dc00000 // ldr q0, [x0]
	WORD $0x4e23d403 // fadd v3.4s, v0.4s, v3.4s
	WORD $0x3c810403 // str q3, [x0], #0x10
	WORD $0xeb06001f // cmp x0, x6
	WORD $0x540000ea // b.ge <EmitRe+0x84>
	WORD $0xbc408441 // ldr s1, [x2], #0x8
	WORD $0xb4000063 // cbz x3, <EmitRe+0x7c>
	WORD $0xbd400000 // ldr s0, [x0]
	WORD $0x1e212801 // fadd s1, s0, s1
	WORD $0xbc004401 // str s1, [x0], #0x4
	WORD $0x17fffff9 // b <EmitRe+0x64>
	RET

// func EmitIm(dst []float32, z []complex64, add bool)
TEXT ·EmitIm(SB), NOSPLIT, $0-49
	MOVD  dst_base+0(FP), R0
	MOVD  dst_len+8(FP), R1
	MOVD  z_base+24(FP), R2
	MOVBU add+48(FP), R3
	WORD $0x927df027 // and x7, x1, #0xfffffffffffffff8
	WORD $0x8b070808 // add x8, x0, x7, lsl #2
	WORD $0x927ef424 // and x4, x1, #0xfffffffffffffffc
	WORD $0x8b040805 // add x5, x0, x4, lsl #2
	WORD $0x8b010806 // add x6, x0, x1, lsl #2
	WORD $0xeb08001f // cmp x0, x8
	WORD $0x5400016a // b.ge <EmitIm+0x44>
	WORD $0xacc10841 // ldp q1, q2, [x2], #0x20
	WORD $0xacc12c4a // ldp q10, q11, [x2], #0x20
	WORD $0x4e825823 // uzp2 v3.4s, v1.4s, v2.4s
	WORD $0x4e8b594c // uzp2 v12.4s, v10.4s, v11.4s
	WORD $0xb4000083 // cbz x3, <EmitIm+0x3c>
	WORD $0xad402400 // ldp q0, q9, [x0]
	WORD $0x4e23d403 // fadd v3.4s, v0.4s, v3.4s
	WORD $0x4e2cd52c // fadd v12.4s, v9.4s, v12.4s
	WORD $0xac813003 // stp q3, q12, [x0], #0x20
	WORD $0x17fffff5 // b <EmitIm+0x14>
	WORD $0xeb05001f // cmp x0, x5
	WORD $0x540000ea // b.ge <EmitIm+0x64>
	WORD $0xacc10841 // ldp q1, q2, [x2], #0x20
	WORD $0x4e825823 // uzp2 v3.4s, v1.4s, v2.4s
	WORD $0xb4000063 // cbz x3, <EmitIm+0x60>
	WORD $0x3dc00000 // ldr q0, [x0]
	WORD $0x4e23d403 // fadd v3.4s, v0.4s, v3.4s
	WORD $0x3c810403 // str q3, [x0], #0x10
	WORD $0xeb06001f // cmp x0, x6
	WORD $0x5400010a // b.ge <EmitIm+0x88>
	WORD $0xbd400441 // ldr s1, [x2, #0x4]
	WORD $0x91002042 // add x2, x2, #0x8
	WORD $0xb4000063 // cbz x3, <EmitIm+0x80>
	WORD $0xbd400000 // ldr s0, [x0]
	WORD $0x1e212801 // fadd s1, s0, s1
	WORD $0xbc004401 // str s1, [x0], #0x4
	WORD $0x17fffff8 // b <EmitIm+0x64>
	RET

// func MinMaxRow(row []float32) (minV, maxV float32, minI, maxI int)
TEXT ·MinMaxRow(SB), NOSPLIT, $0-48
	MOVD row_base+0(FP), R0
	MOVD row_len+8(FP), R1
	WORD $0xad404000 // ldp q0, q16, [x0]
	WORD $0x4ea01c01 // mov v1.16b, v0.16b
	WORD $0x4eb01e11 // mov v17.16b, v16.16b
	WORD $0xd2c00029 // mov x9, #0x100000000
	WORD $0xd280004a // mov x10, #0x2
	WORD $0xf2c0006a // movk x10, #0x3, lsl #32
	WORD $0x4e081d22 // mov v2.d[0], x9
	WORD $0x4e181d42 // mov v2.d[1], x10
	WORD $0x4f000485 // movi v5.4s, #0x4
	WORD $0x4ea58452 // add v18.4s, v2.4s, v5.4s
	WORD $0x4ea21c43 // mov v3.16b, v2.16b
	WORD $0x4eb21e53 // mov v19.16b, v18.16b
	WORD $0x4ea21c44 // mov v4.16b, v2.16b
	WORD $0x4eb21e54 // mov v20.16b, v18.16b
	WORD $0x4f000505 // movi v5.4s, #0x8
	WORD $0x9100800a // add x10, x0, #0x20
	WORD $0x8b01080b // add x11, x0, x1, lsl #2
	WORD $0xeb0b015f // cmp x10, x11
	WORD $0x5400022a // b.ge <MinMaxRow+0x8c>
	WORD $0xacc15546 // ldp q6, q21, [x10], #0x20
	WORD $0x4ea58484 // add v4.4s, v4.4s, v5.4s
	WORD $0x4ea58694 // add v20.4s, v20.4s, v5.4s
	WORD $0x6ea6e407 // fcmgt v7.4s, v0.4s, v6.4s
	WORD $0x6ea71cc0 // bit v0.16b, v6.16b, v7.16b
	WORD $0x6ea71c82 // bit v2.16b, v4.16b, v7.16b
	WORD $0x6ea1e4c7 // fcmgt v7.4s, v6.4s, v1.4s
	WORD $0x6ea71cc1 // bit v1.16b, v6.16b, v7.16b
	WORD $0x6ea71c83 // bit v3.16b, v4.16b, v7.16b
	WORD $0x6eb5e616 // fcmgt v22.4s, v16.4s, v21.4s
	WORD $0x6eb61eb0 // bit v16.16b, v21.16b, v22.16b
	WORD $0x6eb61e92 // bit v18.16b, v20.16b, v22.16b
	WORD $0x6eb1e6b6 // fcmgt v22.4s, v21.4s, v17.4s
	WORD $0x6eb61eb1 // bit v17.16b, v21.16b, v22.16b
	WORD $0x6eb61e93 // bit v19.16b, v20.16b, v22.16b
	WORD $0x17ffffef // b <MinMaxRow+0x44>
	WORD $0x6eb0e408 // fcmgt v8.4s, v0.4s, v16.4s
	WORD $0x4e20e609 // fcmeq v9.4s, v16.4s, v0.4s
	WORD $0x4eb2344a // cmgt v10.4s, v2.4s, v18.4s
	WORD $0x4e2a1d29 // and v9.16b, v9.16b, v10.16b
	WORD $0x4ea91d08 // orr v8.16b, v8.16b, v9.16b
	WORD $0x6ea81e00 // bit v0.16b, v16.16b, v8.16b
	WORD $0x6ea81e42 // bit v2.16b, v18.16b, v8.16b
	WORD $0x6ea1e628 // fcmgt v8.4s, v17.4s, v1.4s
	WORD $0x4e21e629 // fcmeq v9.4s, v17.4s, v1.4s
	WORD $0x4eb3346a // cmgt v10.4s, v3.4s, v19.4s
	WORD $0x4e2a1d29 // and v9.16b, v9.16b, v10.16b
	WORD $0x4ea91d08 // orr v8.16b, v8.16b, v9.16b
	WORD $0x6ea81e21 // bit v1.16b, v17.16b, v8.16b
	WORD $0x6ea81e63 // bit v3.16b, v19.16b, v8.16b
	WORD $0x6e004006 // ext v6.16b, v0.16b, v0.16b, #0x8
	WORD $0x6e024047 // ext v7.16b, v2.16b, v2.16b, #0x8
	WORD $0x6ea6e408 // fcmgt v8.4s, v0.4s, v6.4s
	WORD $0x4e20e4c9 // fcmeq v9.4s, v6.4s, v0.4s
	WORD $0x4ea7344a // cmgt v10.4s, v2.4s, v7.4s
	WORD $0x4e2a1d29 // and v9.16b, v9.16b, v10.16b
	WORD $0x4ea91d08 // orr v8.16b, v8.16b, v9.16b
	WORD $0x6ea81cc0 // bit v0.16b, v6.16b, v8.16b
	WORD $0x6ea81ce2 // bit v2.16b, v7.16b, v8.16b
	WORD $0x4ea00806 // rev64 v6.4s, v0.4s
	WORD $0x4ea00847 // rev64 v7.4s, v2.4s
	WORD $0x6ea6e408 // fcmgt v8.4s, v0.4s, v6.4s
	WORD $0x4e20e4c9 // fcmeq v9.4s, v6.4s, v0.4s
	WORD $0x4ea7344a // cmgt v10.4s, v2.4s, v7.4s
	WORD $0x4e2a1d29 // and v9.16b, v9.16b, v10.16b
	WORD $0x4ea91d08 // orr v8.16b, v8.16b, v9.16b
	WORD $0x6ea81cc0 // bit v0.16b, v6.16b, v8.16b
	WORD $0x6ea81ce2 // bit v2.16b, v7.16b, v8.16b
	WORD $0x6e014026 // ext v6.16b, v1.16b, v1.16b, #0x8
	WORD $0x6e034067 // ext v7.16b, v3.16b, v3.16b, #0x8
	WORD $0x6ea1e4c8 // fcmgt v8.4s, v6.4s, v1.4s
	WORD $0x4e21e4c9 // fcmeq v9.4s, v6.4s, v1.4s
	WORD $0x4ea7346a // cmgt v10.4s, v3.4s, v7.4s
	WORD $0x4e2a1d29 // and v9.16b, v9.16b, v10.16b
	WORD $0x4ea91d08 // orr v8.16b, v8.16b, v9.16b
	WORD $0x6ea81cc1 // bit v1.16b, v6.16b, v8.16b
	WORD $0x6ea81ce3 // bit v3.16b, v7.16b, v8.16b
	WORD $0x4ea00826 // rev64 v6.4s, v1.4s
	WORD $0x4ea00867 // rev64 v7.4s, v3.4s
	WORD $0x6ea1e4c8 // fcmgt v8.4s, v6.4s, v1.4s
	WORD $0x4e21e4c9 // fcmeq v9.4s, v6.4s, v1.4s
	WORD $0x4ea7346a // cmgt v10.4s, v3.4s, v7.4s
	WORD $0x4e2a1d29 // and v9.16b, v9.16b, v10.16b
	WORD $0x4ea91d08 // orr v8.16b, v8.16b, v9.16b
	WORD $0x6ea81cc1 // bit v1.16b, v6.16b, v8.16b
	WORD $0x6ea81ce3 // bit v3.16b, v7.16b, v8.16b
	FMOVS F0, minV+24(FP)
	FMOVS F1, maxV+28(FP)
	VMOV  V2.S[0], R9
	MOVD  R9, minI+32(FP)
	VMOV  V3.S[0], R10
	MOVD  R10, maxI+40(FP)
	RET

// func RGBAToGray(dst, src []uint8)
TEXT ·RGBAToGray(SB), NOSPLIT, $0-48
	MOVD dst_base+0(FP), R0
	MOVD dst_len+8(FP), R1
	MOVD src_base+24(FP), R2
	WORD $0xd2826469 // mov x9, #0x1323
	WORD $0xf2a4b229 // movk x9, #0x2591, lsl #16
	WORD $0xf2c0e989 // movk x9, #0x74c, lsl #32
	WORD $0x4e080d3d // dup v29.2d, x9
	WORD $0x4f01241c // movi v28.4s, #0x20, lsl #8
	WORD $0xd2800009 // mov x9, #0x0
	WORD $0x927cec2a // and x10, x1, #0xfffffffffffffff0
	WORD $0xeb0a013f // cmp x9, x10
	WORD $0x5400074a // b.ge <RGBAToGray+0x108>
	WORD $0xacc10841 // ldp q1, q2, [x2], #0x20
	WORD $0xacc16057 // ldp q23, q24, [x2], #0x20
	WORD $0x2f08a423 // ushll v3.8h, v1.8b, #0x0
	WORD $0x6f08a424 // ushll2 v4.8h, v1.16b, #0x0
	WORD $0x2e7dc065 // umull v5.4s, v3.4h, v29.4h
	WORD $0x6e7dc066 // umull2 v6.4s, v3.8h, v29.8h
	WORD $0x2e7dc087 // umull v7.4s, v4.4h, v29.4h
	WORD $0x6e7dc090 // umull2 v16.4s, v4.8h, v29.8h
	WORD $0x4ea6bca5 // addp v5.4s, v5.4s, v6.4s
	WORD $0x4eb0bce7 // addp v7.4s, v7.4s, v16.4s
	WORD $0x4ea7bcb3 // addp v19.4s, v5.4s, v7.4s
	WORD $0x2f08a443 // ushll v3.8h, v2.8b, #0x0
	WORD $0x6f08a444 // ushll2 v4.8h, v2.16b, #0x0
	WORD $0x2e7dc066 // umull v6.4s, v3.4h, v29.4h
	WORD $0x6e7dc070 // umull2 v16.4s, v3.8h, v29.8h
	WORD $0x2e7dc087 // umull v7.4s, v4.4h, v29.4h
	WORD $0x6e7dc091 // umull2 v17.4s, v4.8h, v29.8h
	WORD $0x4eb0bcc6 // addp v6.4s, v6.4s, v16.4s
	WORD $0x4eb1bce7 // addp v7.4s, v7.4s, v17.4s
	WORD $0x4ea7bcd4 // addp v20.4s, v6.4s, v7.4s
	WORD $0x2f08a6e3 // ushll v3.8h, v23.8b, #0x0
	WORD $0x6f08a6e4 // ushll2 v4.8h, v23.16b, #0x0
	WORD $0x2e7dc065 // umull v5.4s, v3.4h, v29.4h
	WORD $0x6e7dc066 // umull2 v6.4s, v3.8h, v29.8h
	WORD $0x2e7dc087 // umull v7.4s, v4.4h, v29.4h
	WORD $0x6e7dc090 // umull2 v16.4s, v4.8h, v29.8h
	WORD $0x4ea6bca5 // addp v5.4s, v5.4s, v6.4s
	WORD $0x4eb0bce7 // addp v7.4s, v7.4s, v16.4s
	WORD $0x4ea7bcb5 // addp v21.4s, v5.4s, v7.4s
	WORD $0x2f08a703 // ushll v3.8h, v24.8b, #0x0
	WORD $0x6f08a704 // ushll2 v4.8h, v24.16b, #0x0
	WORD $0x2e7dc066 // umull v6.4s, v3.4h, v29.4h
	WORD $0x6e7dc070 // umull2 v16.4s, v3.8h, v29.8h
	WORD $0x2e7dc087 // umull v7.4s, v4.4h, v29.4h
	WORD $0x6e7dc091 // umull2 v17.4s, v4.8h, v29.8h
	WORD $0x4eb0bcc6 // addp v6.4s, v6.4s, v16.4s
	WORD $0x4eb1bce7 // addp v7.4s, v7.4s, v17.4s
	WORD $0x4ea7bcd6 // addp v22.4s, v6.4s, v7.4s
	WORD $0x4ebc8673 // add v19.4s, v19.4s, v28.4s
	WORD $0x4ebc8694 // add v20.4s, v20.4s, v28.4s
	WORD $0x4ebc86b5 // add v21.4s, v21.4s, v28.4s
	WORD $0x4ebc86d6 // add v22.4s, v22.4s, v28.4s
	WORD $0x6f320673 // ushr v19.4s, v19.4s, #0xe
	WORD $0x6f320694 // ushr v20.4s, v20.4s, #0xe
	WORD $0x6f3206b5 // ushr v21.4s, v21.4s, #0xe
	WORD $0x6f3206d6 // ushr v22.4s, v22.4s, #0xe
	WORD $0x0e612a73 // xtn v19.4h, v19.4s
	WORD $0x4e612a93 // xtn2 v19.8h, v20.4s
	WORD $0x0e212a73 // xtn v19.8b, v19.8h
	WORD $0x0e612ab5 // xtn v21.4h, v21.4s
	WORD $0x4e612ad5 // xtn2 v21.8h, v22.4s
	WORD $0x0e212ab5 // xtn v21.8b, v21.8h
	WORD $0x6e1806b3 // mov v19.d[1], v21.d[0]
	WORD $0x3ca96813 // str q19, [x0, x9]
	WORD $0x91004129 // add x9, x9, #0x10
	WORD $0xeb0a013f // cmp x9, x10
	WORD $0x54fff90b // b.lt <RGBAToGray+0x24>
	WORD $0xeb01013f // cmp x9, x1
	WORD $0x5400038a // b.ge <RGBAToGray+0x17c>
	WORD $0xacc10841 // ldp q1, q2, [x2], #0x20
	WORD $0x2f08a423 // ushll v3.8h, v1.8b, #0x0
	WORD $0x6f08a424 // ushll2 v4.8h, v1.16b, #0x0
	WORD $0x2e7dc065 // umull v5.4s, v3.4h, v29.4h
	WORD $0x6e7dc066 // umull2 v6.4s, v3.8h, v29.8h
	WORD $0x2e7dc087 // umull v7.4s, v4.4h, v29.4h
	WORD $0x6e7dc090 // umull2 v16.4s, v4.8h, v29.8h
	WORD $0x4ea6bca5 // addp v5.4s, v5.4s, v6.4s
	WORD $0x4eb0bce7 // addp v7.4s, v7.4s, v16.4s
	WORD $0x4ea7bca5 // addp v5.4s, v5.4s, v7.4s
	WORD $0x2f08a443 // ushll v3.8h, v2.8b, #0x0
	WORD $0x6f08a444 // ushll2 v4.8h, v2.16b, #0x0
	WORD $0x2e7dc066 // umull v6.4s, v3.4h, v29.4h
	WORD $0x6e7dc070 // umull2 v16.4s, v3.8h, v29.8h
	WORD $0x2e7dc087 // umull v7.4s, v4.4h, v29.4h
	WORD $0x6e7dc091 // umull2 v17.4s, v4.8h, v29.8h
	WORD $0x4eb0bcc6 // addp v6.4s, v6.4s, v16.4s
	WORD $0x4eb1bce7 // addp v7.4s, v7.4s, v17.4s
	WORD $0x4ea7bcc6 // addp v6.4s, v6.4s, v7.4s
	WORD $0x4ebc84a5 // add v5.4s, v5.4s, v28.4s
	WORD $0x4ebc84c6 // add v6.4s, v6.4s, v28.4s
	WORD $0x6f3204a5 // ushr v5.4s, v5.4s, #0xe
	WORD $0x6f3204c6 // ushr v6.4s, v6.4s, #0xe
	WORD $0x0e6128a5 // xtn v5.4h, v5.4s
	WORD $0x4e6128c5 // xtn2 v5.8h, v6.4s
	WORD $0x0e2128a5 // xtn v5.8b, v5.8h
	WORD $0xfc296805 // str d5, [x0, x9]
	RET

// func SlideCols1(colSum []int32, colSum2 []int64, rsub, radd []uint8)
TEXT ·SlideCols1(SB), NOSPLIT, $0-96
	MOVD colSum_base+0(FP), R0
	MOVD colSum_len+8(FP), R1
	MOVD colSum2_base+24(FP), R2
	MOVD rsub_base+48(FP), R3
	MOVD radd_base+72(FP), R4
	WORD $0xd2800009 // mov x9, #0x0
	WORD $0x927cec2a // and x10, x1, #0xfffffffffffffff0
	WORD $0xeb0a013f // cmp x9, x10
	WORD $0x540006ca // b.ge <SlideCols1+0xe4>
	WORD $0x3ce96880 // ldr q0, [x4, x9]
	WORD $0x3ce96879 // ldr q25, [x3, x9]
	WORD $0x2f08a401 // ushll v1.8h, v0.8b, #0x0
	WORD $0x2f08a722 // ushll v2.8h, v25.8b, #0x0
	WORD $0x6f08a41a // ushll2 v26.8h, v0.16b, #0x0
	WORD $0x6f08a73b // ushll2 v27.8h, v25.16b, #0x0
	WORD $0x6e628423 // sub v3.8h, v1.8h, v2.8h
	WORD $0x4e628424 // add v4.8h, v1.8h, v2.8h
	WORD $0x6e7b875c // sub v28.8h, v26.8h, v27.8h
	WORD $0x4e7b875d // add v29.8h, v26.8h, v27.8h
	WORD $0x0f10a465 // sshll v5.4s, v3.4h, #0x0
	WORD $0x4f10a466 // sshll2 v6.4s, v3.8h, #0x0
	WORD $0x0f10a79e // sshll v30.4s, v28.4h, #0x0
	WORD $0x4f10a79f // sshll2 v31.4s, v28.8h, #0x0
	WORD $0xad404410 // ldp q16, q17, [x0]
	WORD $0x4ea58610 // add v16.4s, v16.4s, v5.4s
	WORD $0x4ea68631 // add v17.4s, v17.4s, v6.4s
	WORD $0xac814410 // stp q16, q17, [x0], #0x20
	WORD $0xad404410 // ldp q16, q17, [x0]
	WORD $0x4ebe8610 // add v16.4s, v16.4s, v30.4s
	WORD $0x4ebf8631 // add v17.4s, v17.4s, v31.4s
	WORD $0xac814410 // stp q16, q17, [x0], #0x20
	WORD $0x0e64c067 // smull v7.4s, v3.4h, v4.4h
	WORD $0x4e64c072 // smull2 v18.4s, v3.8h, v4.8h
	WORD $0x0e7dc385 // smull v5.4s, v28.4h, v29.4h
	WORD $0x4e7dc386 // smull2 v6.4s, v28.8h, v29.8h
	WORD $0x0f20a4f3 // sshll v19.2d, v7.2s, #0x0
	WORD $0x4f20a4f4 // sshll2 v20.2d, v7.4s, #0x0
	WORD $0x0f20a655 // sshll v21.2d, v18.2s, #0x0
	WORD $0x4f20a656 // sshll2 v22.2d, v18.4s, #0x0
	WORD $0x0f20a4ba // sshll v26.2d, v5.2s, #0x0
	WORD $0x4f20a4bb // sshll2 v27.2d, v5.4s, #0x0
	WORD $0x0f20a4de // sshll v30.2d, v6.2s, #0x0
	WORD $0x4f20a4df // sshll2 v31.2d, v6.4s, #0x0
	WORD $0xad406057 // ldp q23, q24, [x2]
	WORD $0x4ef386f7 // add v23.2d, v23.2d, v19.2d
	WORD $0x4ef48718 // add v24.2d, v24.2d, v20.2d
	WORD $0xac816057 // stp q23, q24, [x2], #0x20
	WORD $0xad406057 // ldp q23, q24, [x2]
	WORD $0x4ef586f7 // add v23.2d, v23.2d, v21.2d
	WORD $0x4ef68718 // add v24.2d, v24.2d, v22.2d
	WORD $0xac816057 // stp q23, q24, [x2], #0x20
	WORD $0xad406057 // ldp q23, q24, [x2]
	WORD $0x4efa86f7 // add v23.2d, v23.2d, v26.2d
	WORD $0x4efb8718 // add v24.2d, v24.2d, v27.2d
	WORD $0xac816057 // stp q23, q24, [x2], #0x20
	WORD $0xad406057 // ldp q23, q24, [x2]
	WORD $0x4efe86f7 // add v23.2d, v23.2d, v30.2d
	WORD $0x4eff8718 // add v24.2d, v24.2d, v31.2d
	WORD $0xac816057 // stp q23, q24, [x2], #0x20
	WORD $0x91004129 // add x9, x9, #0x10
	WORD $0xeb0a013f // cmp x9, x10
	WORD $0x54fff98b // b.lt <SlideCols1+0x10>
	WORD $0xeb01013f // cmp x9, x1
	WORD $0x5400036a // b.ge <SlideCols1+0x154>
	WORD $0xfc696881 // ldr d1, [x4, x9]
	WORD $0xfc696862 // ldr d2, [x3, x9]
	WORD $0x2f08a421 // ushll v1.8h, v1.8b, #0x0
	WORD $0x2f08a442 // ushll v2.8h, v2.8b, #0x0
	WORD $0x6e628423 // sub v3.8h, v1.8h, v2.8h
	WORD $0x4e628424 // add v4.8h, v1.8h, v2.8h
	WORD $0x0f10a465 // sshll v5.4s, v3.4h, #0x0
	WORD $0x4f10a466 // sshll2 v6.4s, v3.8h, #0x0
	WORD $0xad404410 // ldp q16, q17, [x0]
	WORD $0x4ea58610 // add v16.4s, v16.4s, v5.4s
	WORD $0x4ea68631 // add v17.4s, v17.4s, v6.4s
	WORD $0xac814410 // stp q16, q17, [x0], #0x20
	WORD $0x0e64c067 // smull v7.4s, v3.4h, v4.4h
	WORD $0x4e64c072 // smull2 v18.4s, v3.8h, v4.8h
	WORD $0x0f20a4f3 // sshll v19.2d, v7.2s, #0x0
	WORD $0x4f20a4f4 // sshll2 v20.2d, v7.4s, #0x0
	WORD $0x0f20a655 // sshll v21.2d, v18.2s, #0x0
	WORD $0x4f20a656 // sshll2 v22.2d, v18.4s, #0x0
	WORD $0xad406057 // ldp q23, q24, [x2]
	WORD $0x4ef386f7 // add v23.2d, v23.2d, v19.2d
	WORD $0x4ef48718 // add v24.2d, v24.2d, v20.2d
	WORD $0xac816057 // stp q23, q24, [x2], #0x20
	WORD $0xad406057 // ldp q23, q24, [x2]
	WORD $0x4ef586f7 // add v23.2d, v23.2d, v21.2d
	WORD $0x4ef68718 // add v24.2d, v24.2d, v22.2d
	WORD $0xac816057 // stp q23, q24, [x2], #0x20
	RET

// func SlideSpill1(wt, q2 []float64, lo, hi []int32, lo2, hi2 []int64,
//	s0, s2 int64) (ns0, ns2 int64)
TEXT ·SlideSpill1(SB), NOSPLIT, $0-176
	MOVD wt_base+0(FP), R0
	MOVD wt_len+8(FP), R1
	MOVD q2_base+24(FP), R2
	MOVD lo_base+48(FP), R3
	MOVD hi_base+72(FP), R4
	MOVD lo2_base+96(FP), R5
	MOVD hi2_base+120(FP), R6
	MOVD s0+144(FP), R7
	MOVD s2+152(FP), R8
	WORD $0x927ff82c // and x12, x1, #0xfffffffffffffffe
	WORD $0xd280000d // mov x13, #0x0
	WORD $0xeb0c01bf // cmp x13, x12
	WORD $0x5400036a // b.ge <SlideSpill1+0x78>
	WORD $0xb8804489 // ldrsw x9, [x4], #0x4
	WORD $0xb880446a // ldrsw x10, [x3], #0x4
	WORD $0xcb0a0129 // sub x9, x9, x10
	WORD $0x8b0900e9 // add x9, x7, x9
	WORD $0x9e6700e0 // fmov d0, x7
	WORD $0x4e181d20 // mov v0.d[1], x9
	WORD $0x4e61d800 // scvtf v0.2d, v0.2d
	WORD $0x3c810400 // str q0, [x0], #0x10
	WORD $0xb880448a // ldrsw x10, [x4], #0x4
	WORD $0xb880446b // ldrsw x11, [x3], #0x4
	WORD $0xcb0b014a // sub x10, x10, x11
	WORD $0x8b0a0127 // add x7, x9, x10
	WORD $0xf84084c9 // ldr x9, [x6], #0x8
	WORD $0xf84084aa // ldr x10, [x5], #0x8
	WORD $0xcb0a0129 // sub x9, x9, x10
	WORD $0x8b090109 // add x9, x8, x9
	WORD $0x9e670101 // fmov d1, x8
	WORD $0x4e181d21 // mov v1.d[1], x9
	WORD $0x4e61d821 // scvtf v1.2d, v1.2d
	WORD $0x3c810441 // str q1, [x2], #0x10
	WORD $0xf84084ca // ldr x10, [x6], #0x8
	WORD $0xf84084ab // ldr x11, [x5], #0x8
	WORD $0xcb0b014a // sub x10, x10, x11
	WORD $0x8b0a0128 // add x8, x9, x10
	WORD $0x910009ad // add x13, x13, #0x2
	WORD $0x17ffffe5 // b <SlideSpill1+0x8>
	WORD $0xeb0101bf // cmp x13, x1
	WORD $0x540001ea // b.ge <SlideSpill1+0xb8>
	WORD $0x9e6200e0 // scvtf d0, x7
	WORD $0xfc008400 // str d0, [x0], #0x8
	WORD $0x9e620101 // scvtf d1, x8
	WORD $0xfc008441 // str d1, [x2], #0x8
	WORD $0xb8804489 // ldrsw x9, [x4], #0x4
	WORD $0xb880446a // ldrsw x10, [x3], #0x4
	WORD $0xcb0a0129 // sub x9, x9, x10
	WORD $0x8b0900e7 // add x7, x7, x9
	WORD $0xf84084c9 // ldr x9, [x6], #0x8
	WORD $0xf84084aa // ldr x10, [x5], #0x8
	WORD $0xcb0a0129 // sub x9, x9, x10
	WORD $0x8b090108 // add x8, x8, x9
	WORD $0x910005ad // add x13, x13, #0x1
	WORD $0x17fffff1 // b <SlideSpill1+0x78>
	MOVD R7, ns0+160(FP)
	MOVD R8, ns2+168(FP)
	RET

// func SlideCols4(colSum []int32, colSum2 []int64, rsub, radd []uint8, cn int)
TEXT ·SlideCols4(SB), NOSPLIT, $0-104
	MOVD colSum_base+0(FP), R0
	MOVD colSum2_base+24(FP), R1
	MOVD colSum2_len+32(FP), R2
	MOVD rsub_base+48(FP), R3
	MOVD radd_base+72(FP), R4
	MOVD cn+96(FP), R5
	WORD $0x6f07e7fe // movi v30.2d, #0xffffffffffffffff
	WORD $0xf1000cbf // cmp x5, #0x3
	WORD $0x54000061 // b.ne <SlideCols4+0x14>
	WORD $0x92ffffe9 // mov x9, #0xffffffffffff
	WORD $0x4e080d3e // dup v30.2d, x9
	WORD $0xb4000b22 // cbz x2, <SlideCols4+0x178>
	WORD $0xd2800009 // mov x9, #0x0
	WORD $0xacc10881 // ldp q1, q2, [x4], #0x20
	WORD $0xacc11063 // ldp q3, q4, [x3], #0x20
	WORD $0x2f08a425 // ushll v5.8h, v1.8b, #0x0
	WORD $0x6f08a426 // ushll2 v6.8h, v1.16b, #0x0
	WORD $0x2f08a467 // ushll v7.8h, v3.8b, #0x0
	WORD $0x6f08a470 // ushll2 v16.8h, v3.16b, #0x0
	WORD $0x6e6784a5 // sub v5.8h, v5.8h, v7.8h
	WORD $0x6e7084c6 // sub v6.8h, v6.8h, v16.8h
	WORD $0x2f08a451 // ushll v17.8h, v2.8b, #0x0
	WORD $0x6f08a452 // ushll2 v18.8h, v2.16b, #0x0
	WORD $0x2f08a493 // ushll v19.8h, v4.8b, #0x0
	WORD $0x6f08a494 // ushll2 v20.8h, v4.16b, #0x0
	WORD $0x6e738631 // sub v17.8h, v17.8h, v19.8h
	WORD $0x6e748652 // sub v18.8h, v18.8h, v20.8h
	WORD $0x0f10a4b5 // sshll v21.4s, v5.4h, #0x0
	WORD $0x4f10a4b6 // sshll2 v22.4s, v5.8h, #0x0
	WORD $0x0f10a4d7 // sshll v23.4s, v6.4h, #0x0
	WORD $0x4f10a4d8 // sshll2 v24.4s, v6.8h, #0x0
	WORD $0xad406819 // ldp q25, q26, [x0]
	WORD $0x4eb58739 // add v25.4s, v25.4s, v21.4s
	WORD $0x4eb6875a // add v26.4s, v26.4s, v22.4s
	WORD $0xac816819 // stp q25, q26, [x0], #0x20
	WORD $0xad406819 // ldp q25, q26, [x0]
	WORD $0x4eb78739 // add v25.4s, v25.4s, v23.4s
	WORD $0x4eb8875a // add v26.4s, v26.4s, v24.4s
	WORD $0xac816819 // stp q25, q26, [x0], #0x20
	WORD $0x0f10a635 // sshll v21.4s, v17.4h, #0x0
	WORD $0x4f10a636 // sshll2 v22.4s, v17.8h, #0x0
	WORD $0x0f10a657 // sshll v23.4s, v18.4h, #0x0
	WORD $0x4f10a658 // sshll2 v24.4s, v18.8h, #0x0
	WORD $0xad406819 // ldp q25, q26, [x0]
	WORD $0x4eb58739 // add v25.4s, v25.4s, v21.4s
	WORD $0x4eb6875a // add v26.4s, v26.4s, v22.4s
	WORD $0xac816819 // stp q25, q26, [x0], #0x20
	WORD $0xad406819 // ldp q25, q26, [x0]
	WORD $0x4eb78739 // add v25.4s, v25.4s, v23.4s
	WORD $0x4eb8875a // add v26.4s, v26.4s, v24.4s
	WORD $0xac816819 // stp q25, q26, [x0], #0x20
	WORD $0x2f08a467 // ushll v7.8h, v3.8b, #0x0
	WORD $0x6f08a470 // ushll2 v16.8h, v3.16b, #0x0
	WORD $0x2f08a433 // ushll v19.8h, v1.8b, #0x0
	WORD $0x6f08a434 // ushll2 v20.8h, v1.16b, #0x0
	WORD $0x4e678675 // add v21.8h, v19.8h, v7.8h
	WORD $0x4e708696 // add v22.8h, v20.8h, v16.8h
	WORD $0x4e3e1ca5 // and v5.16b, v5.16b, v30.16b
	WORD $0x4e3e1cc6 // and v6.16b, v6.16b, v30.16b
	WORD $0x4e3e1eb5 // and v21.16b, v21.16b, v30.16b
	WORD $0x4e3e1ed6 // and v22.16b, v22.16b, v30.16b
	WORD $0x0e75c0b7 // smull v23.4s, v5.4h, v21.4h
	WORD $0x4e75c0b8 // smull2 v24.4s, v5.8h, v21.8h
	WORD $0x0e76c0d9 // smull v25.4s, v6.4h, v22.4h
	WORD $0x4e76c0da // smull2 v26.4s, v6.8h, v22.8h
	WORD $0x4eb8bef7 // addp v23.4s, v23.4s, v24.4s
	WORD $0x4ebabf39 // addp v25.4s, v25.4s, v26.4s
	WORD $0x4eb9bef7 // addp v23.4s, v23.4s, v25.4s
	WORD $0x2f08a487 // ushll v7.8h, v4.8b, #0x0
	WORD $0x6f08a490 // ushll2 v16.8h, v4.16b, #0x0
	WORD $0x2f08a453 // ushll v19.8h, v2.8b, #0x0
	WORD $0x6f08a454 // ushll2 v20.8h, v2.16b, #0x0
	WORD $0x4e678675 // add v21.8h, v19.8h, v7.8h
	WORD $0x4e708696 // add v22.8h, v20.8h, v16.8h
	WORD $0x4e3e1e31 // and v17.16b, v17.16b, v30.16b
	WORD $0x4e3e1e52 // and v18.16b, v18.16b, v30.16b
	WORD $0x4e3e1eb5 // and v21.16b, v21.16b, v30.16b
	WORD $0x4e3e1ed6 // and v22.16b, v22.16b, v30.16b
	WORD $0x0e75c238 // smull v24.4s, v17.4h, v21.4h
	WORD $0x4e75c239 // smull2 v25.4s, v17.8h, v21.8h
	WORD $0x0e76c25a // smull v26.4s, v18.4h, v22.4h
	WORD $0x4e76c25b // smull2 v27.4s, v18.8h, v22.8h
	WORD $0x4eb9bf18 // addp v24.4s, v24.4s, v25.4s
	WORD $0x4ebbbf5a // addp v26.4s, v26.4s, v27.4s
	WORD $0x4ebabf18 // addp v24.4s, v24.4s, v26.4s
	WORD $0x0f20a6f9 // sshll v25.2d, v23.2s, #0x0
	WORD $0x4f20a6fa // sshll2 v26.2d, v23.4s, #0x0
	WORD $0x0f20a71b // sshll v27.2d, v24.2s, #0x0
	WORD $0x4f20a71c // sshll2 v28.2d, v24.4s, #0x0
	WORD $0xad404430 // ldp q16, q17, [x1]
	WORD $0x4ef98610 // add v16.2d, v16.2d, v25.2d
	WORD $0x4efa8631 // add v17.2d, v17.2d, v26.2d
	WORD $0xac814430 // stp q16, q17, [x1], #0x20
	WORD $0xad404430 // ldp q16, q17, [x1]
	WORD $0x4efb8610 // add v16.2d, v16.2d, v27.2d
	WORD $0x4efc8631 // add v17.2d, v17.2d, v28.2d
	WORD $0xac814430 // stp q16, q17, [x1], #0x20
	WORD $0x91002129 // add x9, x9, #0x8
	WORD $0xeb02013f // cmp x9, x2
	WORD $0x54fff54b // b.lt <SlideCols4+0x1c>
	RET
