#!/usr/bin/env python3
"""Generate ../simd_arm64.s from kernels.S + simd_arm64_tmpl.s.

Go's arm64 assembler (as of Go 1.24) has no un-fused vector FP arithmetic
(only VFMLA/VFMLS, which the bit-exactness contract forbids), so the NEON
kernel bodies are written as real ARM64 assembly in kernels.S, assembled
with clang, and spliced into the Go asm template as WORD streams with the
disassembly kept alongside each word. The template owns the TEXT frames
and every argument load/store (so `go vet` still checks FP offsets); each
`// GENBODY: <symbol>` marker line is replaced by that symbol's body.

Rules enforced here:
  - bodies must be relocation-free (no literal pools / external refs);
    constants are built with mov/movk/movi/fmov immediates
  - each body must end with a single `ret`, which is dropped — the
    template provides Go's RET at the splice point, so internal branches
    that target the final ret still land correctly
  - only x0-x15 and v0-v31 may be used (checked textually): x18/x26-x30
    are reserved by the Go runtime/assembler on arm64

Run via: go generate ./internal/simd  (requires clang + llvm-objdump)
"""

import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
KERNELS = HERE / "kernels.S"
TEMPLATE = HERE / "simd_arm64_tmpl.s"
OUT = HERE.parent / "simd_arm64.s"

BANNED_REG = re.compile(r"\b(x1[6-9]|x2[0-9]|x30|w1[6-9]|w2[0-9]|w30|sp)\b")


def run(*cmd):
    p = subprocess.run(cmd, capture_output=True, text=True)
    if p.returncode != 0:
        sys.exit(f"$ {' '.join(cmd)}\n{p.stdout}{p.stderr}")
    return p.stdout


def tool(*names):
    for n in names:
        if subprocess.run(["which", n], capture_output=True).returncode == 0:
            return n
    sys.exit(f"none of {names} found")


def main():
    clang = tool("clang", "clang-18")
    objdump = tool("llvm-objdump", "llvm-objdump-18")
    readelf = tool("llvm-readelf", "llvm-readelf-18")

    obj = HERE / "kernels.o"
    run(clang, "-target", "aarch64-linux-gnu", "-march=armv8-a", "-c",
        str(KERNELS), "-o", str(obj))

    relocs = run(readelf, "-r", str(obj))
    if ".text" in relocs:
        sys.exit("kernels.S produced text relocations — constants must be "
                 "register-built, not literal-pool loads:\n" + relocs)

    # Parse per-symbol (word, disasm) lists.
    dis = run(objdump, "-d", str(obj))
    bodies: dict[str, list[tuple[str, str]]] = {}
    cur = None
    for line in dis.splitlines():
        m = re.match(r"^[0-9a-f]+ <(\w+)>:$", line)
        if m:
            cur = m.group(1)
            bodies[cur] = []
            continue
        m = re.match(r"^\s+[0-9a-f]+:\s+([0-9a-f]{8})\s+(.*)$", line)
        if m and cur:
            word, text = m.groups()
            text = re.sub(r"\s+", " ", text.split("//")[0]).strip()
            bodies[cur].append((word, text))

    for name, ins in bodies.items():
        if not ins or ins[-1][1] != "ret":
            sys.exit(f"{name}: body must end with exactly one ret")
        bodies[name] = ins[:-1]
        for _, text in bodies[name]:
            if BANNED_REG.search(text):
                sys.exit(f"{name}: uses a reserved register: {text}")

    out_lines = [
        "// Code generated by internal/simd/_gen/gen.py from kernels.S. "
        "DO NOT EDIT.",
        "// Regenerate with: go generate ./internal/simd",
        "",
    ]
    used = set()
    for line in (TEMPLATE.read_text()).splitlines():
        m = re.match(r"^\s*// GENBODY: (\w+)\s*$", line)
        if not m:
            out_lines.append(line)
            continue
        name = m.group(1)
        if name not in bodies:
            sys.exit(f"template wants body {name}, not found in kernels.S")
        used.add(name)
        for word, text in bodies[name]:
            out_lines.append(f"\tWORD $0x{word} // {text}")
    unused = set(bodies) - used
    if unused:
        sys.exit(f"bodies never spliced: {sorted(unused)}")

    OUT.write_text("\n".join(out_lines) + "\n")
    obj.unlink()
    print(f"wrote {OUT} ({sum(len(b) for b in bodies.values())} instructions "
          f"across {len(bodies)} kernels)")


if __name__ == "__main__":
    main()
