#!/usr/bin/env python3
"""Parses raw benchmark outputs into benchdata.json and renders the
measured matrix (matrix.md) next to it — the whole benchmark-report
pipeline in one script; every measured number the README references is
generated here.

Inputs (any subset; missing values are carried over from the existing
benchdata.json so partial re-measurements stay coherent per field):

  --asm FILE      `go test -bench . -benchtime 5x -cpu 1,4` output
                  (default build with the AVX2 kernels; keys asm1/asm4
                  for Match, agray1/agray4 for MatchGray)
  --go FILE       the same run with -tags purego — scalar safe mode
                  (keys go1/go4, gray1/gray4)
  --native FILE   `bench/cpp/native_bench cpp/scenes N` output
  --mem FILE      concatenated `memprobe -impl {baseline,cvmatch,gray}` lines
  --native-mem KB peak RSS (VmHWM kB) of native_bench on the 1080p/128 scene
  --parity FILE   `bench/cmd/paritystat` output (drift column)
  --opencv TEXT   native OpenCV version string
  --host TEXT     one-line description of the machine

Usage: python3 docs/collect.py [flags] -o out/benchdata.json
(matrix.md is written next to the -o file)
"""
import argparse
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

# Everything matrix_markdown reads; carried-over keys outside this
# vocabulary (e.g. from retired implementations) are pruned on every run.
SCENE_KEYS = {"native", "ngray",
              "asm1", "asm4", "go1", "go4", "agray1", "agray4", "gray1", "gray4"}
MEM_KEYS = {"native", "match", "gray", "baseline"}


def parse_go_bench(path):
    """BenchmarkMatch/scene[-N] <iters> <ns> ns/op -> {(kind, scene, cpus): ms}"""
    out = {}
    rx = re.compile(
        r"^Benchmark(Match|MatchGray)/([\w]+?)(?:-(\d+))?\s+\d+\s+([\d.]+) ns/op")
    for line in open(path):
        m = rx.match(line)
        if not m:
            continue
        kind, scene, cpus, ns = m.group(1), m.group(2), m.group(3) or "1", m.group(4)
        out[(kind, scene, int(cpus))] = float(ns) / 1e6
    return out


def parse_native(path):
    """scene <best> ms <core> ms -> color e2e; gray:scene <best> ms -> gray
    e2e. Returns ({scene: ms}, {scene: gray_ms})."""
    out, gray = {}, {}
    rx = re.compile(r"^(\w+)\s+([\d.]+) ms\s+([\d.]+) ms")
    rg = re.compile(r"^gray:(\w+)\s+([\d.]+) ms")
    for line in open(path):
        m = rx.match(line)
        if m:
            out[m.group(1)] = float(m.group(2))
            continue
        m = rg.match(line)
        if m:
            gray[m.group(1)] = float(m.group(2))
    return out, gray


def parse_mem(path):
    """impl=X ... peakHWM=N kB -> {impl: MB}"""
    out = {}
    rx = re.compile(r"impl=(\w+).*peakHWM=(\d+) kB")
    for line in open(path):
        m = rx.search(line)
        if m:
            out[m.group(1)] = float(m.group(2)) / 1024.0
    return out


def parse_parity(path):
    """paritystat lines: scene=X worst_abs=E ... -> {scene: worst_abs}"""
    out = {}
    rx = re.compile(r"scene=(\w+) worst_abs=([\d.eE+-]+)")
    for line in open(path):
        m = rx.match(line)
        if m:
            out[m.group(1)] = float(m.group(2))
    return out




# (scene key, table label)
LAYOUT = [
    ("window1600_button96x32", "Window 1600×1000 · button 96×32"),
    ("window1600_icon24x24", "Window 1600×1000 · icon 24×24"),
    ("window1600_panel300x200", "Window 1600×1000 · panel 300×200"),
    ("noise720p_sub96", "Noise 1280×720 · sub 96×96"),
    ("noise1080p_sub128", "Noise 1920×1080 · sub 128×128"),
    ("noise1080p_sub32", "Noise 1920×1080 · sub 32×32"),
    ("noise640_alpha", "Noise 640×480 · varying alpha, 4ch"),
    ("window4k_button96x32", "Window 3840×2160 · button 96×32"),
    ("noise4k_sub256", "Noise 3840×2160 · sub 256×256"),
    ("photo_fruits", "fruits 512×480 · sub 80×80"),
    ("photo_baboon", "baboon 512×512 · sub 64×64"),
    ("photo_building", "building 868×600 · sub 100×100"),
    ("photo_graf1", "graf1 800×640 · sub 120×120"),
    ("photo_starry_night", "starry_night 752×600 · sub 128×128"),
]


def matrix_markdown(data):
    """The measured amd64 three-way (native / asm / no-asm), markdown only."""
    sc, mem = data["scenes"], data.get("mem", {})
    parity = data.get("parity", {})
    lines = [
        "# cvmatch measured benchmark matrix",
        "",
        "Auto-generated by the `bench-charts` workflow (weekly + on demand);",
        "raw data in [`benchdata.json`](benchdata.json), rendered by the main",
        "branch's `docs/collect.py`. Do not edit by hand.",
        "",
        "`Match`, milliseconds. Native C++ is the best of 7 end-to-end runs,",
        "single-threaded because that is how OpenCV's `matchTemplate` runs;",
        "the cvmatch columns are `go test -benchtime 5x` averages from",
        "`-cpu 1,4` — asm = the default build (AVX2 kernels), no-asm = the",
        "`-tags purego` build. max|Δ| is the worst per-element deviation vs",
        "native (element gate 1e-3).",
        "",
        "**amd64** — " + (data.get("host") or "the amd64 CI runner") + ":",
        "",
        "| scene | native C++ | asm 1T | asm 4T | no-asm 1T | no-asm 4T | max\\|Δ\\| |",
        "|---|---|---|---|---|---|---|",
    ]
    keys = ("native", "asm1", "asm4", "go1", "go4")
    for key, label in LAYOUT:
        s = sc.get(key)
        if not s or not all(k in s for k in keys):
            continue
        go_cells = [s[k] for k in keys[1:]]
        best = min(go_cells)
        fmt = [f"{s['native']:.1f}"]
        fmt += [f"**{v:.1f}**" if v == best else f"{v:.1f}" for v in go_cells]
        w = parity.get(key, {}).get("amd64")
        fmt.append(f"{w:.1e}" if w is not None else "—")
        lines.append(f"| {label} | " + " | ".join(fmt) + " |")

    gkeys = ("ngray", "agray1", "agray4", "gray1", "gray4")
    grows = [(key, label) for key, label in LAYOUT
             if sc.get(key) and all(k in sc[key] for k in gkeys)]
    if grows:
        lines += [
            "",
            "`MatchGray`, milliseconds — the production call shape (convert to",
            "gray once per call, match single-channel). The native column is",
            "the same end-to-end shape in C++: cvtColor(RGBA→GRAY, BT.601) on",
            "both images + 1-channel matchTemplate + minMaxLoc, single-threaded.",
            "",
            "| scene | native gray C++ | asm 1T | asm 4T | no-asm 1T | no-asm 4T |",
            "|---|---|---|---|---|---|",
        ]
        for key, label in grows:
            s = sc[key]
            cells = [s[k] for k in gkeys[1:]]
            best = min(cells)
            fmt = [f"{s['ngray']:.1f}"]
            fmt += [f"**{v:.1f}**" if v == best else f"{v:.1f}" for v in cells]
            lines.append(f"| {label} | " + " | ".join(fmt) + " |")
        gs = [sc[key] for key, _ in grows]
        rg1 = [s["ngray"] / s["agray1"] for s in gs]
        rg4 = [s["ngray"] / s["agray4"] for s in gs]
        rgo4 = [s["ngray"] / s["gray4"] for s in gs]
        lines += [
            "",
            f"Gray like-for-like (1T vs 1T): the asm build beats native gray by",
            f"{min(rg1):.1f}–{max(rg1):.1f}x. In the production shape — cvmatch threaded, native",
            f"single-threaded as it ships — asm at 4T holds {min(rg4):.1f}–{max(rg4):.1f}x, and even",
            f"the no-asm build at 4T (every non-amd64 platform) holds",
            f"{min(rgo4):.1f}–{max(rgo4):.1f}x over single-threaded native gray.",
        ]
    else:
        g = sc.get("noise1080p_sub128", {})
        if all(k in g for k in ("agray1", "agray4", "gray1", "gray4")):
            lines += [
                "",
                f"`MatchGray` at 1080p/128 for scale: asm {g['agray1']:.1f} / {g['agray4']:.1f} ms,",
                f"no-asm {g['gray1']:.1f} / {g['gray4']:.1f} ms (1T / 4T). Native C++ has no gray",
                "row in this refresh — the gray baseline column appears once a",
                "run with the gray-enabled native harness publishes.",
            ]
    # Derived claims, regenerated with the data so prose never goes stale.
    # Only scenes carrying all three contenders feed the like-for-like
    # ranges, so a partial re-measurement can never mix scene sets.
    full = [s for s in sc.values() if all(k in s for k in ("native", "asm1", "go1"))]
    r_amd = [s["go1"] / s["asm1"] for s in full]
    r_nat = [s["native"] / s["asm1"] for s in full]
    r_natgo = [s["native"] / s["go1"] for s in full]
    r_thr = [s["asm1"] / s["asm4"] for s in sc.values() if "asm1" in s and "asm4" in s]
    if full:
        lines += [
            "",
            f"**Measured summary (single-threaded, like-for-like):** the default asm",
            f"build beats native OpenCV C++ by {min(r_nat):.1f}–{max(r_nat):.1f}x and runs",
            f"{min(r_amd):.1f}–{max(r_amd):.1f}x faster than the -tags purego build — the",
            f"proof that the amd64 assembly layer earns its keep. The no-asm build",
            f"is the algorithm-only comparison (what every non-amd64 platform",
            f"runs): {min(r_natgo):.2f}–{max(r_natgo):.2f}x vs native on the same scenes.",
        ]
    if r_thr:
        lines += [
            "",
            f"Internal multi-threading (4 workers, bit-identical output at any worker",
            f"count) further improves cvmatch by up to {max(r_thr):.1f}x on the multi-tile",
            "scenes — the 4T columns above. It is a product feature, not part of the",
            "vs-native comparison: OpenCV's matchTemplate does not thread, so the",
            "headline numbers are 1T vs 1T.",
        ]
    if all(k in mem for k in ("native", "match", "gray", "baseline")):
        lines += [
            "",
            "Peak process memory for one 1080p/128 match (VmHWM, fresh process,",
            f"default build): native OpenCV {mem['native']:.0f} MB, `Match` {mem['match']:.0f} MB,",
            f"`MatchGray` {mem['gray']:.0f} MB, idle Go baseline {mem['baseline']:.0f} MB.",
        ]
    drift = [(w, sk) for sk, per in parity.items() for w in per.values()]
    if drift:
        w, ws = max(drift)
        alarm = " **⚠ above the 7e-4 soft alarm — investigate before the next deviation ships.**" if w > 7e-4 else ""
        opencv = data.get("opencv", "")
        lines += [
            "",
            f"**Tolerance drift vs native OpenCV{' ' + opencv if opencv else ''}:** worst per-element",
            f"|Δ| this refresh {w:.1e} ({ws}); element gate 1e-3, owner budget 5e-2.{alarm}",
        ]
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--asm")
    ap.add_argument("--go")
    ap.add_argument("--native")
    ap.add_argument("--mem")
    ap.add_argument("--native-mem", type=float, help="VmHWM kB")
    ap.add_argument("--parity", help="paritystat output")
    ap.add_argument("--opencv", help="native OpenCV version string")
    ap.add_argument("--host")
    ap.add_argument("-o", "--out", default=os.path.join(HERE, "benchdata.json"))
    args = ap.parse_args()

    data = {"host": "", "scenes": {}, "mem": {}}
    if os.path.exists(args.out):
        data = json.load(open(args.out))

    if args.host:
        data["host"] = args.host
    data.pop("hostArm64", None)
    scenes = data.setdefault("scenes", {})

    def put_go(path, match_key, gray_key, suffix):
        for (kind, scene, cpus), ms in parse_go_bench(path).items():
            key = (match_key if kind == "Match" else gray_key) + suffix + str(cpus)
            scenes.setdefault(scene, {})[key] = round(ms, 1)

    if args.native:
        nat, ngray = parse_native(args.native)
        for scene, ms in nat.items():
            scenes.setdefault(scene, {})["native"] = round(ms, 1)
        for scene, ms in ngray.items():
            scenes.setdefault(scene, {})["ngray"] = round(ms, 1)
    if args.asm:
        put_go(args.asm, "asm", "agray", "")
    if args.go:
        put_go(args.go, "go", "gray", "")
    if args.mem:
        mem = parse_mem(args.mem)
        for k_src, k_dst in (("baseline", "baseline"), ("cvmatch", "match"), ("gray", "gray")):
            if k_src in mem:
                data.setdefault("mem", {})[k_dst] = round(mem[k_src], 1)
    if args.native_mem:
        data.setdefault("mem", {})["native"] = round(args.native_mem / 1024.0, 1)
    if args.parity:
        for scene, w in parse_parity(args.parity).items():
            data.setdefault("parity", {}).setdefault(scene, {})["amd64"] = w
    if args.opencv:
        data["opencv"] = args.opencv

    for s in scenes.values():
        for k in list(s):
            if k not in SCENE_KEYS:
                del s[k]
    for k in list(data.get("mem", {})):
        if k not in MEM_KEYS:
            del data["mem"][k]
    for per in data.get("parity", {}).values():
        for k in list(per):
            if k != "amd64":
                del per[k]

    json.dump(data, open(args.out, "w"), indent=1, sort_keys=True)
    matrix = os.path.join(os.path.dirname(os.path.abspath(args.out)), "matrix.md")
    open(matrix, "w").write(matrix_markdown(data))
    print(f"wrote {args.out} and {matrix}", file=sys.stderr)


if __name__ == "__main__":
    main()
